LPS-197235 Remove unneeded space
is-solutions-delivery/liferay-portal pull request #4857
Opened 2023-09-27 12:57 UTC by joanagrego

2023-09-27 12:57 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-27 12:58 UTC, joanagrego commented
ci:test:sf

2023-09-27 13:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/4853/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4853/jenkins-report.html">here</a>.</b></p>

2023-09-27 13:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4853/">test-portal-source-format#4853</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4853/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/4857">is-solutions-delivery#4857</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2432343533">[master] ci:test:sf - joanagrego &gt; is-solutions-delivery - PR#4857 - 2023-09-27[05:59:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/4153/">publish-testray-report#4153</a><br/></div></div>

2023-09-27 13:18 UTC, joanagrego commented
ci:test:sf

2023-09-27 13:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 35 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/01053c88c48f03141cb7ff1cf4fdbe8207b8cbc0">01053c88c48f03141cb7ff1cf4fdbe8207b8cbc0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joanagrego/liferay-portal/tree/LPS-197235">LPS-197235</a><br/>Branch GIT ID: <a href="https://github.com/joanagrego/liferay-portal/commit/a66df771a93d28c0e02441408b2cb27f5015038d">a66df771a93d28c0e02441408b2cb27f5015038d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/2634/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2634/jenkins-report.html">here</a>.</h5></details></html>

2023-09-27 13:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/2634/">test-portal-source-format#2634</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/2634/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/4857">is-solutions-delivery#4857</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2432381089">[master] ci:test:sf - joanagrego &gt; is-solutions-delivery - PR#4857 - 2023-09-27[06:18:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/10806/">publish-testray-report#10806</a><br/></div></div>

2023-09-27 16:32 UTC, kevenleone requested changes

2023-09-27 16:32 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedSolutions/PurchasedSolutions.tsx
> +													</label>
```suggestion
                                                                                                         <label
														className="ml-2"
														htmlFor="agreeToTermsAndConditions"
													>
														I agree to the
													</label>
													<label className="ml-4">
														<ClayLink
															displayType="primary"
															href="https://www.liferay.com/en/legal/marketplace-terms-of-service"
														>
															Terms & Conditions
														</ClayLink>
													</label>
													
```

2023-09-27 16:32 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedSolutions/PurchasedSolutions.tsx
> +													</label>
No reverse 😄

2023-09-27 16:33 UTC, kevenleone requested changes

2023-09-27 16:33 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedSolutions/PurchasedSolutions.tsx
> +	const hasAllValidations = isValid && agreeToTermsAndConditions;
```suggestion
	const hasAllValidations = agreeToTermsAndConditions  && isValid;
```

2023-09-27 16:43 UTC, joanagrego commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedSolutions/PurchasedSolutions.tsx
> +													</label>
Done!

2023-09-27 16:44 UTC, joanagrego commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedSolutions/PurchasedSolutions.tsx
> +	const hasAllValidations = isValid && agreeToTermsAndConditions;
Done.

2023-09-27 17:13 UTC, joanagrego commented
ci:test:sf

2023-09-27 17:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/4162/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4162/jenkins-report.html">here</a>.</b></p>

2023-09-27 17:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7f12032a2dadc28dd81c77b9ab6c94ac03ccd7fc">7f12032a2dadc28dd81c77b9ab6c94ac03ccd7fc</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joanagrego/liferay-portal/tree/LPS-197235">LPS-197235</a><br/>Branch GIT ID: <a href="https://github.com/joanagrego/liferay-portal/commit/605a3bed243743a050b0100330524cf3e59fe33d">605a3bed243743a050b0100330524cf3e59fe33d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/4162/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4162/jenkins-report.html">here</a>.</h5></details></html>

2023-09-27 19:23 UTC, joanagrego commented
liferay/ci:test:site-initializer-liferay-marketplace

2023-09-27 19:23 UTC, joanagrego commented
ci:test:site-initializer-liferay-marketplace

2023-09-27 20:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>site-initializer-liferay-marketplace</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/14772/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/14772/jenkins-report.html">here</a>.</b></p>

2023-09-27 22:45 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:site-initializer-liferay-marketplace - 0 out of 4 jobs passed in 2 hours 43 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/39">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1377401_14772</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/42f8479cff77adb4bffd37384f79a8d69ddf5858">42f8479cff77adb4bffd37384f79a8d69ddf5858</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/01053c88c48f03141cb7ff1cf4fdbe8207b8cbc0">01053c88c48f03141cb7ff1cf4fdbe8207b8cbc0</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2432581189">EE Development Acceptance (master) - 38 - 2023-09-27[08:39:26]</a></p><details><summary><strong>ci:test:site-initializer-liferay-marketplace - 0 out of 4 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/14772/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/264284/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/367086/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/367085/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li></ul></li></ul></div></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/14772/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/264284//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><ol><li><div><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/264284//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MP2CustomerDashboard_AssertCustomerIsTakenBackDashboard_">LocalFile.MP2CustomerDashboard#AssertCustomerIsTakenBackDashboard</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.MP2CustomerDashboard_AssertCustomerIsTakenBackDashboard/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.MP2CustomerDashboard_AssertCustomerIsTakenBackDashboard/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.MP2CustomerDashboard_AssertCustomerIsTakenBackDashboard/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/264284//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MP2CustomerDashboard_AssertNewMemberListedAndGreyedOut_">LocalFile.MP2CustomerDashboard#AssertNewMemberListedAndGreyedOut</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.MP2CustomerDashboard_AssertNewMemberListedAndGreyedOut/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.MP2CustomerDashboard_AssertNewMemberListedAndGreyedOut/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.MP2CustomerDashboard_AssertNewMemberListedAndGreyedOut/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/264284//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MP2CustomerDashboard_CanSeeMemberDetails_">LocalFile.MP2CustomerDashboard#CanSeeMemberDetails</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.MP2CustomerDashboard_CanSeeMemberDetails/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.MP2CustomerDashboard_CanSeeMemberDetails/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.MP2CustomerDashboard_CanSeeMemberDetails/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li>...</li></ol></div></li><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/367086//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/367086//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_MP2PublisherDashboard_AssertTheDetailsOfTheEmail_">LocalFile.MP2PublisherDashboard#AssertTheDetailsOfTheEmail</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.MP2PublisherDashboard_AssertTheDetailsOfTheEmail/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.MP2PublisherDashboard_AssertTheDetailsOfTheEmail/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.MP2PublisherDashboard_AssertTheDetailsOfTheEmail/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-37/test-portal-acceptance-pullrequest(master)/14772/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptan [...]

2023-09-27 22:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/14772/">test-portal-acceptance-pullrequest(master)#14772</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/14772/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>site-initializer-liferay-marketplace<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/4857">is-solutions-delivery#4857</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2432698975">[master] ci:test:site-initializer-liferay-marketplace - joanagrego &gt; is-solutions-delivery - PR#4857 - 2023-09-27[13:01:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/31501/">publish-testray-report#31501</a><br/></div></div>

2023-09-28 00:57 UTC, kevenleone approved these changes
LGTM 🔥

2023-09-28 11:53 UTC, kevenleone commented
ci:test:relevant

2023-09-28 13:51 UTC, LuanaKSilva commented
Hey @joanagrego, I analyzed the errors and none of them are caused because of your PR. Feel free to go ahead.

2023-09-28 14:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/7955/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7955/jenkins-report.html">here</a>.</b></p>

2023-09-28 15:55 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 28 out of 30 jobs passed</h3><h3>:x: ci:test:relevant - 53 out of 60 jobs passed in 1 hour 54 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bf9b8657efe5ca1a0766d81c9fc35edc731e0aae">bf9b8657efe5ca1a0766d81c9fc35edc731e0aae</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bf9b8657efe5ca1a0766d81c9fc35edc731e0aae">bf9b8657efe5ca1a0766d81c9fc35edc731e0aae</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2433179745">EE Development Acceptance (master) - 42 - 2023-09-28[00:41:26]</a></p><details><summary><strong>ci:test:stable - 28 out of 30 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li>build-iw-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/658802/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/846302/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/287774/"><strike>functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</strike></a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/744073/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/690850/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/744074/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280186/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/713602/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/602195/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/602190/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/602191/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/713600/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/602193/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/690849/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/713601/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/368126/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309903/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/291279/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/658804/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309902/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/264601/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/368128/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729540/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/744076/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/287775/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-mysql57-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/789479/"><strike>portal-license-smoke-mysql57-jdk8/0/0</strike></a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280188/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/245187/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280187/">unit-jdk8_stable/0/0</a></li></ul></li><li>workspaces-compile-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/295390/">workspaces-compile-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>28 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 53 out of 60 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/7955/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/658802/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/846302/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/287773/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/245188/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/368127/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/602194/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/287774/"><strike>functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</strike></a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-27 [...]

2023-09-28 16:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/7955/">test-portal-acceptance-pullrequest(master)#7955</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7955/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/4857">is-solutions-delivery#4857</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2433312371">[master] ci:test:relevant - joanagrego &gt; is-solutions-delivery - PR#4857 - 2023-09-28[07:00:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/19201/">publish-testray-report#19201</a><br/></div></div>

2023-09-28 16:41 UTC, joanagrego commented
Resent --> [PR](https://github.com/brianchandotcom/liferay-portal/pull/141494)

2023-09-28 16:41 UTC, closed without merging