LPS-185953
is-solutions-delivery/liferay-portal pull request #4862
Opened 2023-09-27 19:01 UTC by joelrocha68

2023-09-27 19:20 UTC, joelrocha68 commented
ci:test:sf

2023-09-27 19:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/8291/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8291/jenkins-report.html">here</a>.</b></p>

2023-09-27 19:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/42f8479cff77adb4bffd37384f79a8d69ddf5858">42f8479cff77adb4bffd37384f79a8d69ddf5858</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joelrocha68/liferay-portal/tree/LPS-185953">LPS-185953</a><br/>Branch GIT ID: <a href="https://github.com/joelrocha68/liferay-portal/commit/4d6015a086f562436236183200ebb24f1c478b4e">4d6015a086f562436236183200ebb24f1c478b4e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8291/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8291/jenkins-report.html">here</a>.</h5></details></html>

2023-09-27 19:59 UTC, styller1 requested changes

2023-09-27 19:59 UTC, styller1 commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/osb-site-initializer-customer-portal-test/src/testFunctional/macros/CP2Utils.macro
> +		AssertElementPresent(
The member name is missing an M, the correct one should be "TeamMembers"

2023-09-27 20:10 UTC, joelrocha68 commented
ci:test:sf

2023-09-27 20:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/6737/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6737/jenkins-report.html">here</a>.</b></p>

2023-09-27 20:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8291/">test-portal-source-format#8291</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8291/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/4862">is-solutions-delivery#4862</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2432635566">[master] ci:test:sf - joelrocha68 &gt; is-solutions-delivery - PR#4862 - 2023-09-27[12:20:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/31493/">publish-testray-report#31493</a><br/></div></div>

2023-09-27 20:20 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/371d73c6fec5cdd2c8caa3dd4884cd6b349516a3">371d73c6fec5cdd2c8caa3dd4884cd6b349516a3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joelrocha68/liferay-portal/tree/LPS-185953">LPS-185953</a><br/>Branch GIT ID: <a href="https://github.com/joelrocha68/liferay-portal/commit/81b8f5bde07f05587e48e14c1d6f5ac7e530cac3">81b8f5bde07f05587e48e14c1d6f5ac7e530cac3</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6737/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6737/jenkins-report.html">here</a>.</h5><div><p>POSHI Validation Failure<pre>     [exec]  errors in POSHI
     [exec] 
     [exec] 
     [exec] Invalid macro command CP2Utils#assertCardTeamMebersActivation at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/osb-site-initializer-customer-portal-test/src/testFunctional/tests/CP2ManageProductUsersLXC.testcase:99
     [exec]    92 |                text = "Set to Active",
     [exec]    93 |                value = 3809080);
     [exec]    94 |        \}
     [exec]    95 |
     [exec]    96 |        task ("Then I assert that manage product user appears in team members") \{
     [exec]    97 |            CP2NavigationMenu.goToTeamMembers();
     [exec]    98 |
     [exec]  &gt; 99 |            CP2Utils.assertCardTeamMebersActivation(title = "Manage Liferay Experience Cloud Users");
     [exec]   100 |        \}
     [exec]   101 |    \}
     [exec]   102 |
     [exec]   103 |\}
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] Sep 27, 2023 1:20:14 PM com.liferay.poshi.core.PoshiValidation validateDeprecatedFunction
     [exec] WARNING: Use of function "AssertTextEquals#assertPartialText" contains deprecated selenium method at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/portal-workflow-kaleo-forms/portal-workflow-kaleo-forms-test/src/testFunctional/macros/KaleoFormsAdmin.macro:758
     [exec] Sep 27, 2023 1:20:14 PM com.liferay.poshi.core.PoshiValidation validateDeprecatedFunction
     [exec] WARNING: Use of function "AssertTextEquals#assertPartialText" contains deprecated selenium method at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommercePriceFragment.testcase:2402
     [exec] Sep 27, 2023 1:20:14 PM com.liferay.poshi.core.PoshiValidation validateDeprecatedFunction
     [exec] WARNING: Use of function "AssertTextEquals#assertPartialText" contains deprecated selenium method at:
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/publications/ManagePublications.testcase:320
     [exec] Sep 27, 2023 1:20:14 PM com.liferay.poshi.core.PoshiValidation validateDeprecatedFunction
     [exec] WARNING: Use of function "AssertTextEquals#assertPartialText" contains deprecated selenium method at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommercePriceFragment.testcase:2406
     [exec] Sep 27, 2023 1:20:14 PM com.liferay.poshi.core.PoshiValidation validateDeprecatedFunction
     [exec] WARNING: Use of function "AssertTextEquals#assertPartialText" contains deprecated selenium method at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/portal-workflow-kaleo-forms/portal-workflow-kaleo-forms-test/src/testFunctional/macros/KaleoFormsAdmin.macro:997
     [exec] Sep 27, 2023 1:20:14 PM com.liferay.poshi.core.PoshiValidation validateDeprecatedFunction
     [exec] WARNING: Use of function "AssertTextEquals#assertPartialText" contains deprecated selenium method at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommercePriceFragment.testcase:2438
     [exec] Sep 27, 2023 1:20:14 PM com.liferay.poshi.core.PoshiValidation validateDeprecatedFunction
     [exec] WARNING: Use of function "AssertTextEquals#assertPartialText" contains deprecated selenium method at:
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/SearchBarSuggestions.testcase:894
     [exec] Sep 27, 2023 1:20:14 PM com.liferay.poshi.core.PoshiValidation validateDeprecatedFunction
     [exec] WARNING: Use of function "AssertTextEquals#assertPartialText" contains deprecated selenium method at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommercePriceFragment.testcase:2442
     [exec] Sep 27, 2023 1:20:14 PM com.liferay.poshi.core.PoshiValidation validateDeprecatedFunction
     [exec] WARNING: Use of function "AssertTextEquals#assertPartialText" contains deprecated selenium method at:
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/documentmanagement/documentsadministration/DMLocalStaging.testcase:2093
     [exec] Sep 27, 2023 1:20:14 PM com.liferay.poshi.core.PoshiValidation validateDeprecatedFunction
     [exec] WARNING: Use of function "AssertTextEquals#assertPartialText" contains deprecated selenium method at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommercePriceFragment.testcase:2474
     [exec] Sep 27, 2023 1:20:14 PM com.liferay.poshi.core.PoshiValidation validateDeprecatedFunction
     [exec] WARNING: Use of function "AssertTextEquals#assertPartialText" contains deprecated selenium method at:
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CommercePriceFragment.testcase:2478
     [exec] Exception in thread "main" java.lang.Exception
     [exec]   at com.liferay.poshi.core.PoshiValidation._throwExceptions(PoshiValidation.java:2125)
     [exec]   at com.liferay.poshi.core.PoshiValidation.validate(PoshiValidation.java:139)
     [exec]   at com.liferay.poshi.core.PoshiValidation.main(PoshiValidation.java:66)
     [exec] 
     [exec] &gt; Task :validatePoshi FAILED</pre></p></div></details></html>

2023-09-27 20:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6737/">test-portal-source-format#6737</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6737/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/4862">is-solutions-delivery#4862</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2432639189">[master] ci:test:sf - joelrocha68 &gt; is-solutions-delivery - PR#4862 - 2023-09-27[13:11:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/4323/">publish-testray-report#4323</a><br/></div></div>

2023-09-28 12:18 UTC, joelrocha68 commented
ci:test:sf

2023-09-28 13:47 UTC, joelrocha68 commented
ci:stop

2023-09-28 14:03 UTC, joelrocha68 commented
ci:test:sf

2023-09-28 14:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/7473/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7473/jenkins-report.html">here</a>.</b></p>

2023-09-28 14:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a0ac7f47c45f749ea975840916381f258b455c07">a0ac7f47c45f749ea975840916381f258b455c07</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/joelrocha68/liferay-portal/tree/LPS-185953">LPS-185953</a><br/>Branch GIT ID: <a href="https://github.com/joelrocha68/liferay-portal/commit/7b504929ad434bed6f5bc7ef8e6e00614218efd2">7b504929ad434bed6f5bc7ef8e6e00614218efd2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7473/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7473/jenkins-report.html">here</a>.</h5></details></html>

2023-09-28 14:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7473/">test-portal-source-format#7473</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7473/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/4862">is-solutions-delivery#4862</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2433245160">[master] ci:test:sf - joelrocha68 &gt; is-solutions-delivery - PR#4862 - 2023-09-28[07:04:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/4634/">publish-testray-report#4634</a><br/></div></div>

2023-09-28 16:14 UTC, joelrocha68 commented
ci:test:osb-site-initializer-customer-portal:nocompile

2023-09-28 16:14 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2023-09-28 18:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>osb-site-initializer-customer-portal</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/10181/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10181/jenkins-report.html">here</a>.</b></p>

2023-09-28 20:58 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:osb-site-initializer-customer-portal - 4 out of 20 jobs passed in 2 hours 58 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/43">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1277401_10181</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e2ece40ab83db4a4d94593d4d2b3fd1802dfef50">e2ece40ab83db4a4d94593d4d2b3fd1802dfef50</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bf9b8657efe5ca1a0766d81c9fc35edc731e0aae">bf9b8657efe5ca1a0766d81c9fc35edc731e0aae</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2433179745">EE Development Acceptance (master) - 42 - 2023-09-28[00:41:26]</a></p><details><summary><strong>ci:test:osb-site-initializer-customer-portal - 4 out of 20 jobs PASSED</strong></summary><div><h4>16 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/10181/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729820/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/766450/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729819/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/766451/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/277263/"><strike>functional-tomcat90-mysql57-jdk8/0/4</strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280428/"><strike>functional-tomcat90-mysql57-jdk8/0/5</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729821/"><strike>functional-tomcat90-mysql57-jdk8/0/6</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729822/"><strike>functional-tomcat90-mysql57-jdk8/0/7</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/757613/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/744571/"><strike>functional-tomcat90-mysql57-jdk8/0/9</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/757614/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/602658/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/297141/"><strike>functional-tomcat90-mysql57-jdk8/0/12</strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280429/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/766635/"><strike>functional-tomcat90-mysql57-jdk8/0/14</strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/280430/"><strike>functional-tomcat90-mysql57-jdk8/0/15</strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/277261/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729818/"><strike>functional-tomcat90-mysql57-jdk8/0/17</strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/277262/">functional-tomcat90-mysql57-jdk8/0/18</a></li></ul></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10181/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729819//consoleText">functional-tomcat90-mysql57-jdk8/0/2</a><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729819//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CP2TeamMembers_IsMaxNumberCorrect_">LocalFile.CP2TeamMembers#IsMaxNumberCorrect</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-27/test-portal-acceptance-pullrequest(master)/10181/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.CP2TeamMembers_IsMaxNumberCorrect/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-27/test-portal-acceptance-pullrequest(master)/10181/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.CP2TeamMembers_IsMaxNumberCorrect/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-27/test-portal-acceptance-pullrequest(master)/10181/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.CP2TeamMembers_IsMaxNumberCorrect/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-27/test-portal-acceptance-pullrequest(master)/10181/functional-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729819//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CP2TeamMembers_IsPartnerManagerShowingUp_">LocalFile.CP2TeamMembers#IsPartnerManagerShowingUp</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-27/test-portal-acceptance-pullrequest(master)/10181/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.CP2TeamMembers_IsPartnerManagerShowingUp/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-27/test-portal-acceptance-pullrequest(master)/10181/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.CP2TeamMembers_IsPartnerManagerShowingUp/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-27/test-portal-acceptance-pullrequest(master)/10181/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.CP2TeamMembers_IsPartnerManagerShowingUp/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-09/test-1-27/test-portal-acceptance-pullrequest(master)/10181/functional-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/729819//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CP2TeamMembers_IsPartnerMemberShowingU [...]

2023-09-28 21:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/10181/">test-portal-acceptance-pullrequest(master)#10181</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10181/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>osb-site-initializer-customer-portal<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/4862">is-solutions-delivery#4862</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2433474759">[master] ci:test:osb-site-initializer-customer-portal - joelrocha68 &gt; is-solutions-delivery - PR#4862 - 2023-09-28[11:00:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/22073/">publish-testray-report#22073</a><br/></div></div>

2023-09-29 13:47 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-09-29 13:47 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-09-29 13:48 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/forward-pullrequest/455//consoleFull)

2023-09-29 13:54 UTC, liferay-continuous-integration commented
Error has occurred while attempting to forward pull request to `brianchandotcom`. Retrying in 1 minute...
See console log for detail:[Full Console](https://test-1-25.liferay.com/job/forward-pullrequest/455//consoleFull)

2023-09-29 13:59 UTC, liferay-continuous-integration commented
Error has occurred while attempting to forward pull request to `brianchandotcom`. Retrying in 1 minute...
See console log for detail:[Full Console](https://test-1-25.liferay.com/job/forward-pullrequest/455//consoleFull)

2023-09-29 14:00 UTC, closed without merging

2023-09-29 14:00 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/141553
[Console](https://test-1-25.liferay.com/job/forward-pullrequest/455//consoleFull)