LPS-195690 Customer - License Selection for DXP Apps - Trial
is-solutions-delivery/liferay-portal pull request #4868
Opened 2023-09-28 19:38 UTC by juliocezar96

2023-09-28 19:38 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-28 19:38 UTC, juliocezar96 commented
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-195690 Customer - License Selection for DXP Apps - Trial (2c)</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-195690">Customer - License Selection for DXP Apps - Trial (2c)</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Story</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>High</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>0/3 Completed</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Development</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Julio Cesar de Oliveira Guimaraes</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Matt Hartel</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

33 files changed, 3749 insertions(+), 759 deletions(-)

This PR is too huge for one to review :broken_heart: 

![Batman](https://raw.githubusercontent.com/kevenleone/gh/main/images/no-way.gif)

2023-09-28 19:46 UTC, juliocezar96 commented
ci:test:sf

2023-09-28 19:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/4928/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4928/jenkins-report.html">here</a>.</b></p>

2023-09-28 19:50 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/42659c54e3dca3e2509eb3b938bffd22386e65e0">42659c54e3dca3e2509eb3b938bffd22386e65e0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliocezar96/liferay-portal/tree/LPS-195690">LPS-195690</a><br/>Branch GIT ID: <a href="https://github.com/juliocezar96/liferay-portal/commit/11b29021579f604f1959dfbed8ebc48f9597ffd1">11b29021579f604f1959dfbed8ebc48f9597ffd1</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4928/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4928/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Truncated message :
     [java] /opt/dev/projects/github/liferay-portal/workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/assets/icons/icon_info_circle_full.svg expected:&lt;&lt;svg [fill="none" height="18" viewBox="0 0 16 18" width="16" xmlns="http://www.w3.org/2000/svg"&gt;
     [java]   &lt;mask height="15" id="mask0_2076_9872" maskUnits="userSpaceOnUse" style="mask-type:alpha" width="16" x="0" y="2"&gt;
     [java]     &lt;mask fill="white" id="path-1-inside-1_2076_9872"&gt;
     [java]       &lt;path d="M14.947 9.05998L13.707 7.64665L13.8803 5.77332C13.9137 5.43998 13.687 5.13332 13.367 5.05998L11.527 4.63998L10.567 3.01998C10.3937 2.73332 10.0403 2.61332 9.73367 2.74665L8.00034 3.49998L6.27367 2.75998C5.96701 2.62665 5.60701 2.74665 5.44034 3.03332L4.47367 4.64665L2.64034 5.05998C2.31367 5.13332 2.08701 5.43332 2.12034 5.77332L2.29367 7.63998L1.05367 9.05998C0.833672 9.31332 0.833672 9.68665 1.05367 9.93998L2.29367 11.3533L2.12034 13.2333C2.08701 13.5667 2.31367 13.8733 2.63367 13.9467L4.47367 14.3666L5.43367 15.98C5.60701 16.2667 5.96034 16.3867 6.27367 16.2533L8.00034 15.5L9.72701 16.24C10.0337 16.3733 10.3937 16.2533 10.5603 15.9667L11.5203 14.3467L13.3603 13.9267C13.687 13.8533 13.907 13.5466 13.8737 13.2133L13.7003 11.34L14.9403 9.92665C15.167 9.68665 15.167 9.31332 14.947 9.05998Z" /&gt;
     [java]     &lt;/mask&gt;</pre></details></html>

2023-09-28 19:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4928/">test-portal-source-format#4928</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4928/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/4868">is-solutions-delivery#4868</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2433406562">[master] ci:test:sf - juliocezar96 &gt; is-solutions-delivery - PR#4868 - 2023-09-28[12:47:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/4725/">publish-testray-report#4725</a><br/></div></div>

2023-09-28 20:08 UTC, juliocezar96 commented
ci:test:sf

2023-09-28 20:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/7428/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7428/jenkins-report.html">here</a>.</b></p>

2023-09-28 20:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/315ce3bec2745bc455b89af9960aca5ab919ac7e">315ce3bec2745bc455b89af9960aca5ab919ac7e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/juliocezar96/liferay-portal/tree/LPS-195690">LPS-195690</a><br/>Branch GIT ID: <a href="https://github.com/juliocezar96/liferay-portal/commit/0f8494506e76515ad0fdec4d1ddd6ed77838fd1a">0f8494506e76515ad0fdec4d1ddd6ed77838fd1a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7428/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7428/jenkins-report.html">here</a>.</h5></details></html>

2023-09-28 20:18 UTC, juliocezar96 commented
Just starting reviewing :)

2023-09-28 20:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7428/">test-portal-source-format#7428</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7428/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/4868">is-solutions-delivery#4868</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2433426704">[master] ci:test:sf - juliocezar96 &gt; is-solutions-delivery - PR#4868 - 2023-09-28[13:08:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/27721/">publish-testray-report#27721</a><br/></div></div>

2023-09-29 02:20 UTC, silasbsi commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/GetAppPage/components/LicenseCard/index.tsx
> +	licensetiers,
Please, change this name.
```suggestion
	licenseTiers,
```

2023-09-29 02:24 UTC, silasbsi commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/GetAppPage/components/LicenseSelector/index.tsx
> +					}
Please, change this code.
```suggestion
					onClick={() => trialSKU ? setSelectedTimeline('trial') : {}}
```

2023-09-29 02:28 UTC, silasbsi commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/GetAppPage/components/PaidTimeline/index.scss
If the file does not have a function, remove it.

2023-09-29 02:37 UTC, silasbsi requested changes
I added some suggestions.

2023-10-02 14:29 UTC, kevenleone commented
@juliocezar96 can you fix conflicts?

2023-10-02 14:29 UTC, closed without merging