ISSD-1364 raplace expando column
is-solutions-delivery/liferay-portal pull request #5027
Opened 2023-10-24 14:34 UTC by Andrefes565

2023-10-24 14:34 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-30 17:55 UTC, nNilton requested changes

2023-10-30 17:55 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test/src/testIntegration/java/com/liferay/site/initializer/extender/internal/test/BundleSiteInitializerTest.java
> +	private void _assertPermissions() throws Exception {_assertRoles();
why did you do that?

2023-10-30 18:00 UTC, nNilton requested changes

2023-10-30 18:00 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java
> +
please move this behavior to a proper method responsible to handle expando columns

2023-10-31 19:32 UTC, nNilton commented
please put the prefix on every single commit (ISSD-????)

2023-10-31 19:36 UTC, nNilton requested changes

2023-10-31 19:36 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender-test/src/testIntegration/java/com/liferay/site/initializer/extender/internal/test/BundleSiteInitializerTest.java
> +
please sort

2023-10-31 19:36 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java
> +		ExpandoColumnLocalService expandoColumnLocalService,
sort

2023-10-31 19:36 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java
> +		_expandoColumnLocalService = expandoColumnLocalService;
sort

2023-10-31 19:36 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java
> +				_expandoColumnLocalService.getExpandoColumns(-1, -1);
you dont need to get all expandoColumns once again

2023-10-31 19:36 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/BundleSiteInitializer.java
> +	private final ExpandoColumnLocalService _expandoColumnLocalService;
sort

2023-10-31 19:36 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/SiteInitializerExtender.java
> +				_layoutLocalService, _layoutPageTemplateEntryLocalService, _expandoColumnLocalService,
sort

2023-10-31 19:36 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/SiteInitializerExtender.java
> +				_layoutLocalService, _layoutPageTemplateEntryLocalService, _expandoColumnLocalService,
sort

2023-10-31 19:36 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/SiteInitializerExtension.java
> +		ExpandoColumnLocalService expandoColumnLocalService,
sort

2023-10-31 19:36 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/SiteInitializerExtension.java
> +			layoutLocalService, layoutPageTemplateEntryLocalService, expandoColumnLocalService,
sort

2023-10-31 19:36 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/SiteInitializerFactoryImpl.java
> +			_layoutLocalService, _layoutPageTemplateEntryLocalService, _expandoColumnLocalService,
sort

2023-10-31 19:36 UTC, nNilton commented on modules/apps/site-initializer/site-initializer-extender/site-initializer-extender/src/main/java/com/liferay/site/initializer/extender/internal/SiteInitializerFactoryImpl.java
> +	@Reference
sort

2023-11-01 20:29 UTC, closed without merging

2023-11-06 19:08 UTC, Andrefes565 commented
ci:reopen

2023-11-06 19:08 UTC, liferay-continuous-integration commented
GitHub error message: state cannot be changed. The expandoColumnReplace branch was force-pushed or recreated.

2023-11-06 19:12 UTC, Andrefes565 commented
Reopen pull request