ISSD-1497
is-solutions-delivery/liferay-portal pull request #5065
Opened 2023-10-31 22:24 UTC by eliasantosf

2023-10-31 22:24 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-31 22:30 UTC, eliasantosf commented
ci:test:sf

2023-10-31 22:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/5156/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5156/jenkins-report.html">here</a>.</b></p>

2023-10-31 22:34 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5e0cf78cc6a36ab268036d8e3fe803805d9410ba">5e0cf78cc6a36ab268036d8e3fe803805d9410ba</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/ISSD-1497">ISSD-1497</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/6272698cfb36d090d3b8dacddba90068d01e1d45">6272698cfb36d090d3b8dacddba90068d01e1d45</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5156/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5156/jenkins-report.html">here</a>.</h5><pre>     [exec] warning "@liferay/npm-scripts &gt; script-ext-html-webpack-plugin@2.1.4" has incorrect peer dependency "html-webpack-plugin@^3.0.0 || ^4.0.0".
     [exec] [4/4] Building fresh packages...
     [exec] Done in 4.68s.
     [exec] 
     [exec] &gt; Task :portalWorkspacesYarnCheckFormat FAILED
     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts lint &amp;&amp; liferay-npm-scripts format:check
     [exec] /opt/dev/projects/github/liferay-portal/workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedAppsDashboard/Apps/Licenses.tsx
     [exec]   8:1  error  imports must be grouped (unexpected blank line before: "../../../components/DashboardTable/DashboardEmptyTable")  @liferay/group-imports
     [exec]   14:15  error  Curly braces are unnecessary here.  react/jsx-curly-brace-presence
     [exec]   15:17  error  Curly braces are unnecessary here.  react/jsx-curly-brace-presence
     [exec]   17:10  error  Curly braces are unnecessary here.  react/jsx-curly-brace-presence
     [exec] 
     [exec] ��� 4 problems (4 errors, 0 warnings)
     [exec]   4 errors and 0 warnings potentially fixable with the `--fix` option.
     [exec] 
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] Gradle build finished at 2023-10-31 22:33:34.330.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':portalWorkspacesYarnCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':portalWorkspacesYarnCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:145)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)</pre></details></html>

2023-10-31 22:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5156/">test-portal-source-format#5156</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5156/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5065">is-solutions-delivery#5065</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2450201507">[master] ci:test:sf - eliasantosf &gt; is-solutions-delivery - PR#5065 - 2023-10-31[15:30:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/19793/">publish-testray-report#19793</a><br/></div></div>

2023-11-01 12:27 UTC, eliasantosf commented
ci:test:sf

2023-11-01 12:33 UTC, silasbsi requested changes
I added some suggestions

2023-11-01 12:33 UTC, silasbsi commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/components/DashboardTable/PurchasedAppsDashboardTableRow.tsx
> +							Manage License Key(s)
Please, use the i18n here.

2023-11-01 12:33 UTC, silasbsi commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedAppsDashboard/Apps/AppOutlet.tsx
> +				Back to My Apps
Please, use i18n here.

2023-11-01 12:33 UTC, silasbsi commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedAppsDashboard/Apps/Licenses.tsx
> +			title={'No Licenses yet'}
Please, use i18n here.

2023-11-01 12:33 UTC, silasbsi commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedAppsDashboard/Apps/Licenses.tsx
> +			description1={'Create new licenses and they will show up here.'}
Please, use i18n here.

2023-11-01 12:33 UTC, silasbsi commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedAppsDashboard/Apps/Licenses.tsx
> +			buttonName={'Create License Key'}
Please, use i18n here.

2023-11-01 12:33 UTC, silasbsi commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedAppsDashboard/Apps/AppOutlet.tsx
> +						Details
Please, use i18n here.

2023-11-01 12:33 UTC, silasbsi commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedAppsDashboard/Apps/AppOutlet.tsx
> +						Licenses
Please, use i18n here.

2023-11-01 12:33 UTC, silasbsi commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedAppsDashboard/Apps/Licenses.tsx
> +			title="No Licenses yet"
Please, use i18n here.

2023-11-01 12:33 UTC, silasbsi commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedAppsDashboard/Apps/Licenses.tsx
> +			description1="Create new licenses and they will show up here."
Please, use i18n here.

2023-11-01 12:33 UTC, silasbsi commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedAppsDashboard/Apps/Licenses.tsx
> +			buttonName="Create License Key"
Please, use i18n here.

2023-11-01 12:33 UTC, silasbsi commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedAppsDashboard/Apps/enums/AppTabType.ts
> +export enum AppTabType {
Please change this name to something like AppTabEnum.

2023-11-01 12:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/86f4019b3f827e3f9cc989c3c8ba587c6b29e929">86f4019b3f827e3f9cc989c3c8ba587c6b29e929</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/ISSD-1497">ISSD-1497</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/6662cbfb9dc532c7154a7d2376da24ddf14aadeb">6662cbfb9dc532c7154a7d2376da24ddf14aadeb</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5237/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5237/jenkins-report.html">here</a>.</h5></details></html>

2023-11-01 12:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5237/">test-portal-source-format#5237</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5237/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5065">is-solutions-delivery#5065</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2450488164">[master] ci:test:sf - eliasantosf &gt; is-solutions-delivery - PR#5065 - 2023-11-01[05:27:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/19457/">publish-testray-report#19457</a><br/></div></div>

2023-11-01 12:39 UTC, joanagrego approved these changes

2023-11-01 13:01 UTC, eliasantosf commented
ci:test:sf

2023-11-01 13:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/5938/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5938/jenkins-report.html">here</a>.</b></p>

2023-11-01 13:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/86f4019b3f827e3f9cc989c3c8ba587c6b29e929">86f4019b3f827e3f9cc989c3c8ba587c6b29e929</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/ISSD-1497">ISSD-1497</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/2d78f8082b7503c8cde49dbbefc47c96e1566606">2d78f8082b7503c8cde49dbbefc47c96e1566606</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5938/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5938/jenkins-report.html">here</a>.</h5></details></html>

2023-11-01 14:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5938/">test-portal-source-format#5938</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5938/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5065">is-solutions-delivery#5065</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2450534443">[master] ci:test:sf - eliasantosf &gt; is-solutions-delivery - PR#5065 - 2023-11-01[06:01:52]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/22662/">publish-testray-report#22662</a><br/></div></div>

2023-11-01 17:45 UTC, eliasantosf commented
ci:test:sf

2023-11-01 17:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/5550/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5550/jenkins-report.html">here</a>.</b></p>

2023-11-01 17:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8a01fc9cc1153585d2bb30ea811249f96ccbf570">8a01fc9cc1153585d2bb30ea811249f96ccbf570</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/ISSD-1497">ISSD-1497</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/8d076f00dec23ba31bddc248934fc182c52f1ff4">8d076f00dec23ba31bddc248934fc182c52f1ff4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5550/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5550/jenkins-report.html">here</a>.</h5></details></html>

2023-11-01 18:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5550/">test-portal-source-format#5550</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5550/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5065">is-solutions-delivery#5065</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2450611910">[master] ci:test:sf - eliasantosf &gt; is-solutions-delivery - PR#5065 - 2023-11-01[10:49:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/3371/">publish-testray-report#3371</a><br/></div></div>

2023-11-02 15:24 UTC, kevenleone commented
Just starting reviewing :)

2023-11-03 03:00 UTC, kevenleone commented
resent: https://github.com/brianchandotcom/liferay-portal/pull/143179

2023-11-03 03:00 UTC, closed without merging