LRQA-83366
is-solutions-delivery/liferay-portal pull request #5093
Opened 2023-11-03 18:16 UTC by Italo-gabriel

2023-11-03 18:16 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-11-03 18:25 UTC, Italo-gabriel commented
ci:test:sf

2023-11-03 18:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9d0995d359ee7f2689d63f7c7649d3159fb1c482">9d0995d359ee7f2689d63f7c7649d3159fb1c482</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Italo-gabriel/liferay-portal/tree/LRQA-83366">LRQA-83366</a><br/>Branch GIT ID: <a href="https://github.com/Italo-gabriel/liferay-portal/commit/b40aa8409dfce6eef07c2a7fe2a6264a08cb6197">b40aa8409dfce6eef07c2a7fe2a6264a08cb6197</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-source-format/3462/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3462/jenkins-report.html">here</a>.</h5></details></html>

2023-11-03 18:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-1.liferay.com/job/test-portal-source-format/3462/">test-portal-source-format#3462</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3462/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5093">is-solutions-delivery#5093</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2452427875">[master] ci:test:sf - Italo-gabriel &gt; is-solutions-delivery - PR#5093 - 2023-11-03[11:26:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/22955/">publish-testray-report#22955</a><br/></div></div>

2023-11-03 21:07 UTC, MGabriellaS requested changes
Thanks @Italo-gabriel  for work on this!
Please take a look on these comments below!
cc: @vinicius-paes

2023-11-03 21:07 UTC, MGabriellaS commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPOrganizationForm.testcase
> +		task ("When the Employee user create a request") {
Just a typo here, could you change this task to: `"When the Employee user creates a request"`

2023-11-03 21:07 UTC, MGabriellaS commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPOrganizationForm.testcase
> +		task ("Then the Employee user view a Request Created and also view Organization Created") {
Just a typo here, could you change this task to: `"Then the Employee user can see the Request  and Organization Created on listing"`

2023-11-03 21:07 UTC, MGabriellaS commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPOrganizationForm.testcase
> +		task ("When the Employee user submit an organization form without a required field filled in") {
Just a typo here, could you change this task to: `"When the Employee user submits an organization form without a required field filled in"`

2023-11-03 21:07 UTC, MGabriellaS commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPOrganizationForm.testcase
> +		task ("When the Employee user create an organization") {
Just a typo here, could you change this task to: `"When the Employee user creates an organization"`

2023-11-03 21:07 UTC, MGabriellaS commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-evp/osb-site-initializer-evp-test/src/testFunctional/tests/EVPOrganizationForm.testcase
> +		task ("Then The Employee user view a 'Thank you' message and is Redirection to page Organization") {
Just a typo here, could you change this task to: `"Then The Employee user view a 'Thank you' message and is Redirected to page Organization"`

2023-11-06 18:30 UTC, MGabriellaS reviewed
Thanks @Italo-gabriel  for working on this!
LGTM!
cc: @vinicius-paes

2023-11-06 18:36 UTC, vinicius-paes approved these changes

2023-11-06 18:36 UTC, vinicius-paes commented
ci:forward

2023-11-06 18:37 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-11-06 18:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/8217/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8217/jenkins-report.html">here</a>.</b></p>

2023-11-06 18:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/4529/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4529/jenkins-report.html">here</a>.</b></p>

2023-11-06 18:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f63d698232b7b620536bb32f854286b132fcc07a">f63d698232b7b620536bb32f854286b132fcc07a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Italo-gabriel/liferay-portal/tree/LRQA-83366">LRQA-83366</a><br/>Branch GIT ID: <a href="https://github.com/Italo-gabriel/liferay-portal/commit/37b52d274aad99daceb753cff6ebd766875bdcd1">37b52d274aad99daceb753cff6ebd766875bdcd1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/4529/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4529/jenkins-report.html">here</a>.</h5></details></html>

2023-11-06 18:42 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-39.liferay.com/job/test-portal-source-format/4529//consoleFull)

2023-11-06 18:43 UTC, closed without merging

2023-11-06 18:43 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/143319
[Console](https://test-1-39.liferay.com/job/test-portal-source-format/4529//consoleFull)

2023-11-06 18:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/8217/">test-portal-acceptance-pullrequest(master)#8217</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8217/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5093">is-solutions-delivery#5093</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2453475151">[master] ci:test:relevant - Italo-gabriel &gt; is-solutions-delivery - PR#5093 - 2023-11-06[10:37:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/16809/">publish-testray-report#16809</a><br/></div></div>

2023-11-06 18:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/4529/">test-portal-source-format#4529</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4529/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5093">is-solutions-delivery#5093</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2453475255">[master] ci:test:sf - Italo-gabriel &gt; is-solutions-delivery - PR#5093 - 2023-11-06[10:37:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/16810/">publish-testray-report#16810</a><br/></div></div>