ISSD-1554 [Marketplace] Create General Header for Order Details
is-solutions-delivery/liferay-portal pull request #5103
Opened 2023-11-06 13:57 UTC by claricebrasil

2023-11-06 13:58 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-11-06 13:58 UTC, claricebrasil commented
ci:test:sf

2023-11-06 14:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f63d698232b7b620536bb32f854286b132fcc07a">f63d698232b7b620536bb32f854286b132fcc07a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/claricebrasil/liferay-portal/tree/pr-5061-2">pr-5061-2</a><br/>Branch GIT ID: <a href="https://github.com/claricebrasil/liferay-portal/commit/4d865d6763890ebea510fb87e1ca655dd1db88d7">4d865d6763890ebea510fb87e1ca655dd1db88d7</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7532/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7532/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: /opt/dev/projects/github/liferay-portal/workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/assets/icons/purchased_app_icon.svg expected:&lt;&lt;svg [fill="none" height="12" viewBox="0 0 12 12" width="12" xmlns="http://www.w3.org/2000/svg"&gt;
     [java]   &lt;g id="1-color"&gt;
     [java]     &lt;g id="icon"&gt;
     [java]       &lt;path d="M3.91474 1.42084C5.49021 0.191074 8.56176 0.566098 10.307 2.14111C13.9026 5.38024 9.46622 13.2306 5.08599 10.6441C6.37802 10.2374 7.64661 9.4091 8.48829 8.4739L8.48931 8.47275C9.45087 7.39465 9.88909 6.31303 9.90567 5.30869C9.92228 4.30341 9.51549 3.41643 8.86393 2.73445C7.70635 1.52286 5.75886 0.936326 3.91474 1.42084Z" fill="#2E5AAC" /&gt;
     [java]       &lt;path d="M4.7126 10.3976L4.71239 10.3976C4.67053 10.3677 4.62868 10.3379 4.58684 10.3071C4.51709 10.2559 4.44737 10.2024 4.37752 10.1425C3.04765 8.99188 1.95597 7.39296 2.8228 3.5466C2.88057 3.29023 2.94705 3.02387 3.02274 2.74701L3.02281 2.7468C3.09253 2.48181 3.21107 2.25343 3.34642 2.0403C3.36575 2.00986 3.38544 1.97972 3.40537 1.94984C3.87755 1.75658 4.36468 1.6455 4.84845 1.60714C8.23488 1.33867 11.4566 4.63361 8.2349 8.24584C7.37424 9.20213 6.03541 10.0469 4.7126 10.3976Z" fill="#2E5AAC" /&gt;
     [java]       &lt;path d="M1.18982 3.71908C1.68189 3.05478 2.24993 2.56139 2.85726 2.21691C2.79228 2.35274 2.73556 2.49914 2.69353 2.65841C2.07902 4.90694 2.05058 6.51504 2.38518 7.73621C2.72224 8.96637 3.41625 9.76164 4.15456 10.4004L4.15575 10.4014C4.19441 10.4346 4.23294 10.4659 4.27102 10.4957C3.46621 10.6379 2.68423 10.5704 2.05054 10.2063C0.249404 9.20218 -0.196895 5.63179 1.18982 3.71908Z" fill="#2E5AAC" /&gt;
     [java]     &lt;/g&gt;
     [java]   &lt;/g&gt;
     [java] &lt;/svg&gt;]&gt; but was:&lt;&lt;svg [width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"&gt;
     [java] &lt;g id="1-color"&gt;
     [java] &lt;g id="icon"&gt;
     [java] &lt;path d="M3.91474 1.42084C5.49021 0.191074 8.56176 0.566098 10.307 2.14111C13.9026 5.38024 9.46622 13.2306 5.08599 10.6441C6.37802 10.2374 7.64661 9.4091 8.48829 8.4739L8.48931 8.47275C9.45087 7.39465 9.88909 6.31303 9.90567 5.30869C9.92228 4.30341 9.51549 3.41643 8.86393 2.73445C7.70635 1.52286 5.75886 0.936326 3.91474 1.42084Z" fill="#2E5AAC"/&gt;</pre></details></html>

2023-11-06 14:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7532/">test-portal-source-format#7532</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7532/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5103">is-solutions-delivery#5103</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2453305624">[master] ci:test:sf - claricebrasil &gt; is-solutions-delivery - PR#5103 - 2023-11-06[05:59:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/4759/">publish-testray-report#4759</a><br/></div></div>

2023-11-06 14:33 UTC, eliasantosf approved these changes

2023-11-06 15:46 UTC, kevenleone requested changes

2023-11-06 15:46 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedAppsDashboard/Apps/components/OrderDetailsHeader.tsx
> +	productName?: string;
```suggestion
	hasOrderDescription?: boolean;
	hasOrderDetails?: boolean;
	order?: Cart;
	productOwner?: string;
	image?: string;
	name?: string;
```

2023-11-06 15:46 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/PurchasedAppsDashboard/Apps/components/OrderDetailsHeader.tsx
> +	productName,
```suggestion
	hasOrderDescription = false,
	hasOrderDetails = false,
	order,
	productOwner,
	image,
	name,
```

2023-11-06 15:55 UTC, kevenleone commented
Just starting reviewing :)

2023-11-07 12:26 UTC, closed without merging

2023-11-07 12:27 UTC, claricebrasil commented
resent: #143334

2023-11-07 12:27 UTC, claricebrasil commented
resent: https://github.com/brianchandotcom/liferay-portal/pull/143334