ISSD-1329
is-solutions-delivery/liferay-portal pull request #5273
Opened 2023-12-06 17:23 UTC by abfranca

2023-12-06 17:23 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-12-06 17:23 UTC, abfranca commented
ci:test:sf

2023-12-06 17:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/5277/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5277/jenkins-report.html">here</a>.</b></p>

2023-12-06 17:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/26211619f4b2e60bf3793e6a85bf1247625fa77f">26211619f4b2e60bf3793e6a85bf1247625fa77f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/abfranca/liferay-portal/tree/ISSD-1329">ISSD-1329</a><br/>Branch GIT ID: <a href="https://github.com/abfranca/liferay-portal/commit/85b73e13550a42b9f46905b13ef4f3e231c8987d">85b73e13550a42b9f46905b13ef4f3e231c8987d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5277/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5277/jenkins-report.html">here</a>.</h5></details></html>

2023-12-06 17:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5277/">test-portal-source-format#5277</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5277/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5273">is-solutions-delivery#5273</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2471498708">[master] ci:test:sf - abfranca &gt; is-solutions-delivery - PR#5273 - 2023-12-06[09:23:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/20315/">publish-testray-report#20315</a><br/></div></div>

2023-12-07 19:59 UTC, nNilton requested changes

2023-12-07 19:59 UTC, nNilton commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-site-initializer/site-initializer/ddm-templates/learn-category-facet/ddm-template.ftl
> +	id = ""
sort

2023-12-07 19:59 UTC, nNilton commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-site-initializer/site-initializer/ddm-templates/learn-category-facet/ddm-template.ftl
> +<style>
move the style to the start of the article

2023-12-07 20:39 UTC, abfranca commented
ci:test:sf

2023-12-07 20:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/3989/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3989/jenkins-report.html">here</a>.</b></p>

2023-12-07 20:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2f69bb4b3e1d004c918bab40fff3b555d4fee425">2f69bb4b3e1d004c918bab40fff3b555d4fee425</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/abfranca/liferay-portal/tree/ISSD-1329">ISSD-1329</a><br/>Branch GIT ID: <a href="https://github.com/abfranca/liferay-portal/commit/3c4fc5175299902ec7fb01437a0abe187fef124e">3c4fc5175299902ec7fb01437a0abe187fef124e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3989/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3989/jenkins-report.html">here</a>.</h5></details></html>

2023-12-11 13:51 UTC, abfranca commented
ci:test:sf

2023-12-11 13:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/5094/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5094/jenkins-report.html">here</a>.</b></p>

2023-12-11 13:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/839d8c833229e39af7aca40aae16059f4be25bee">839d8c833229e39af7aca40aae16059f4be25bee</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/abfranca/liferay-portal/tree/ISSD-1329">ISSD-1329</a><br/>Branch GIT ID: <a href="https://github.com/abfranca/liferay-portal/commit/eaf6f44cf3fe53c296fecbb0dec335b7f52db96d">eaf6f44cf3fe53c296fecbb0dec335b7f52db96d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5094/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5094/jenkins-report.html">here</a>.</h5></details></html>

2023-12-11 18:35 UTC, nNilton requested changes

2023-12-11 18:35 UTC, nNilton commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-site-initializer/site-initializer/ddm-templates/learn-category-facet/ddm-template.ftl
> +	termDisplayContextClass = ""
sort

2023-12-11 18:35 UTC, nNilton commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-site-initializer/site-initializer/ddm-templates/learn-category-facet/ddm-template.ftl
> +						hasTermDisplayContextHidden = false
sort

2023-12-11 18:35 UTC, nNilton commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-site-initializer/site-initializer/ddm-templates/learn-category-facet/ddm-template.ftl
> +								hasTermDisplayContextHidden = true
sort

2023-12-11 18:35 UTC, nNilton commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-site-initializer/site-initializer/ddm-templates/learn-search-results/ddm-template.ftl
> +	}
sort

2023-12-11 18:35 UTC, nNilton commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-site-initializer/site-initializer/ddm-templates/learn-search-results/ddm-template.ftl
> +							/>
sort

2023-12-11 18:59 UTC, abfranca commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-site-initializer/site-initializer/ddm-templates/learn-category-facet/ddm-template.ftl
> +	termDisplayContextClass = ""
Done.

2023-12-11 19:00 UTC, abfranca commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-site-initializer/site-initializer/ddm-templates/learn-category-facet/ddm-template.ftl
> +								hasTermDisplayContextHidden = true
Done.

2023-12-11 19:00 UTC, abfranca commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-site-initializer/site-initializer/ddm-templates/learn-search-results/ddm-template.ftl
> +	}
Done.

2023-12-11 19:00 UTC, abfranca commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-site-initializer/site-initializer/ddm-templates/learn-search-results/ddm-template.ftl
> +							/>
Done.

2023-12-11 19:03 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/839d8c833229e39af7aca40aae16059f4be25bee">839d8c833229e39af7aca40aae16059f4be25bee</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/abfranca/liferay-portal/tree/ISSD-1329">ISSD-1329</a><br/>Branch GIT ID: <a href="https://github.com/abfranca/liferay-portal/commit/47b11de94a4693fba38d60bbb0fb554183bc519b">47b11de94a4693fba38d60bbb0fb554183bc519b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3013/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3013/jenkins-report.html">here</a>.</h5></details></html>

2023-12-12 15:49 UTC, abfranca commented
ci:test:sf

2023-12-12 15:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/7610/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7610/jenkins-report.html">here</a>.</b></p>

2023-12-12 15:54 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ad700a7ff309d37e95901d678e16b6e56d2b0f84">ad700a7ff309d37e95901d678e16b6e56d2b0f84</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/abfranca/liferay-portal/tree/ISSD-1329">ISSD-1329</a><br/>Branch GIT ID: <a href="https://github.com/abfranca/liferay-portal/commit/a3d744c130c7406b8b4c0838c51a686864c0dbcf">a3d744c130c7406b8b4c0838c51a686864c0dbcf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7610/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7610/jenkins-report.html">here</a>.</h5></details></html>

2023-12-12 15:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7610/">test-portal-source-format#7610</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7610/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5273">is-solutions-delivery#5273</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2473440177">[master] ci:test:sf - abfranca &gt; is-solutions-delivery - PR#5273 - 2023-12-12[07:49:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/4900/">publish-testray-report#4900</a><br/></div></div>

2023-12-12 18:06 UTC, abfranca commented
ci:test:sf

2023-12-12 18:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/7901/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7901/jenkins-report.html">here</a>.</b></p>

2023-12-12 18:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ad700a7ff309d37e95901d678e16b6e56d2b0f84">ad700a7ff309d37e95901d678e16b6e56d2b0f84</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/abfranca/liferay-portal/tree/ISSD-1329">ISSD-1329</a><br/>Branch GIT ID: <a href="https://github.com/abfranca/liferay-portal/commit/62a8221fb3424e6c2a44688d2bfc5f0593400473">62a8221fb3424e6c2a44688d2bfc5f0593400473</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7901/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7901/jenkins-report.html">here</a>.</h5></details></html>

2023-12-13 20:12 UTC, joseabelenda commented
resent:https://github.com/brianchandotcom/liferay-portal/pull/145213

2023-12-13 20:12 UTC, closed without merging