ISSD-1854
is-solutions-delivery/liferay-portal pull request #5275
Opened 2023-12-06 18:12 UTC by abfranca

2023-12-06 18:12 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-12-06 18:13 UTC, abfranca commented
ci:test:sf

2023-12-06 18:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/2433/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2433/jenkins-report.html">here</a>.</b></p>

2023-12-06 18:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2433/">test-portal-source-format#2433</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2433/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5275">is-solutions-delivery#5275</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2471512706">[master] ci:test:sf - abfranca &gt; is-solutions-delivery - PR#5275 - 2023-12-06[10:14:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/10453/">publish-testray-report#10453</a><br/></div></div>

2023-12-07 17:48 UTC, nNilton approved these changes

2023-12-07 18:06 UTC, nNilton requested changes
Site administration is missing

2023-12-07 19:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/2314/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2314/jenkins-report.html">here</a>.</b></p>

2023-12-07 19:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee2717f38bb6f171e594caaa0bcc70a934330ded">ee2717f38bb6f171e594caaa0bcc70a934330ded</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/abfranca/liferay-portal/tree/ISSD-1854">ISSD-1854</a><br/>Branch GIT ID: <a href="https://github.com/abfranca/liferay-portal/commit/1b0c29dcf4acbcbce5346f6bdfa468a389653138">1b0c29dcf4acbcbce5346f6bdfa468a389653138</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2314/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2314/jenkins-report.html">here</a>.</h5></details></html>

2023-12-11 18:15 UTC, nNilton approved these changes

2023-12-13 18:34 UTC, joseabelenda approved these changes

2023-12-13 20:12 UTC, joseabelenda commented
resent:https://github.com/brianchandotcom/liferay-portal/pull/145213

2023-12-13 20:12 UTC, closed without merging