ISSD-2097 [Marketplace] Fix Email templates to Gmail pattern
is-solutions-delivery/liferay-portal pull request #5294
Opened 2023-12-13 17:41 UTC by welitonpe

2023-12-13 17:41 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-12-13 19:01 UTC, welitonpe commented
ci:test:sf

2023-12-13 19:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-source-format/6698/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6698/jenkins-report.html">here</a>.</b></p>

2023-12-13 19:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6698/">test-portal-source-format#6698</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6698/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5294">is-solutions-delivery#5294</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2474161464">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5294 - 2023-12-13[11:01:54]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/3679/">publish-testray-report#3679</a><br/></div></div>

2023-12-13 19:31 UTC, welitonpe commented
ci:test:sf

2023-12-13 19:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/4100/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/4100/jenkins-report.html">here</a>.</b></p>

2023-12-13 19:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6e5f0a88fa4e64410596e1dc897f2906aa46bd6e">6e5f0a88fa4e64410596e1dc897f2906aa46bd6e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/fixesBugs">fixesBugs</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/60fb95fede7890530f28b0b95dd3373dd47c4f5e">60fb95fede7890530f28b0b95dd3373dd47c4f5e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/4100/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/4100/jenkins-report.html">here</a>.</h5></details></html>

2023-12-13 19:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/4100/">test-portal-source-format#4100</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/4100/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5294">is-solutions-delivery#5294</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2474175228">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5294 - 2023-12-13[11:31:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/15660/">publish-testray-report#15660</a><br/></div></div>

2023-12-14 13:48 UTC, juliocezar96 commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/notification-templates/publisher-account-request/en-US.html
> +						</div>
```suggestion
							<img alt="Liferay Logo" src="[$PORTAL_URL$]/documents/d/[$GROUP_KEY$]/liferay_logo-png" style="height: 56.9px; margin-bottom: 32px;  margin-top: 32px; margin-left:auto; margin-right:auto; width: 180px; " />
						</div>
```

2023-12-14 13:50 UTC, juliocezar96 commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/notification-templates/cloud-next-steps-template/en-US.html
> +		<div style="background-color: #fff; border-radius: 16px; border: 1px solid #6b6c7e; margin-bottom: 4rem; margin-top: 4rem;margin-left: auto; margin-right: auto; padding: 3rem; width: 925px;">
```suggestion
		<div style="background-color: #fff; border: 1px solid #6b6c7e; border-radius: 16px;  margin-bottom: 4rem;  margin-left: auto; margin-right: auto;  margin-top: 4rem; padding: 3rem; width: 925px;">
```

2023-12-14 13:50 UTC, juliocezar96 commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/notification-templates/invite-member-template/en-US.html
> +		<div style="background-color: #fff; border-radius: 4px; border: 1px solid #6b6c7e; height: 50rem; margin-top: 6.25rem; padding: 3rem; width: 43.375rem;">
```suggestion
		<div style="background-color: #fff; border: 1px solid #6b6c7e;  border-radius: 4px; height: 50rem; margin-top: 6.25rem; padding: 3rem; width: 43.375rem;">
```

2023-12-14 13:51 UTC, juliocezar96 commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/notification-templates/publisher-account-request/en-US.html
> +				<a href="#" style="background-color: #0b5fff; border-radius: 8px; border: none; color: #fff; height: 2.5rem; margin-top: 2.5rem; padding: 0.5rem 1.5rem; text-decoration: none; width: 10.938rem;">
```suggestion
				<a href="#" style="background-color: #0b5fff; border: none; border-radius: 8px; color: #fff; height: 2.5rem; margin-top: 2.5rem; padding: 0.5rem 1.5rem; text-decoration: none; width: 10.938rem;">
```

2023-12-14 13:53 UTC, juliocezar96 commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/notification-templates/publisher-account-request/en-US.html
> +						</div>
```suggestion
							<img alt="Liferay Logo" src="[$PORTAL_URL$]/documents/d/[$GROUP_KEY$]/liferay_logo-png" style=" height: 56.9px; margin-bottom: 32px; margin-left:auto; margin-right:auto; margin-top: 32px; width: 180px;" />
						</div>
```

2023-12-14 13:54 UTC, juliocezar96 commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/notification-templates/publisher-account-request/en-US.html
> +					<div style="font-size: 14px; text-align:center; ">
```suggestion
					<div style="font-size:14px; text-align:center;">
```

2023-12-14 13:55 UTC, juliocezar96 requested changes
Hey, Nice job! But, I have some suggestions. 🧑‍💻 👀

2023-12-14 15:05 UTC, kevenleone commented
Just starting reviewing :)

2023-12-14 15:21 UTC, kevenleone commented
resent:T https://github.com/brianchandotcom/liferay-portal/pull/145261

2023-12-14 15:21 UTC, closed without merging