ISSD-1450
is-solutions-delivery/liferay-portal pull request #5381
Opened 2024-01-11 20:41 UTC by tiago-ds

2024-01-11 20:41 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-01-11 20:45 UTC, tiago-ds commented
ci:test:sf

2024-01-11 20:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/4977/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/4977/jenkins-report.html">here</a>.</b></p>

2024-01-11 20:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fff775e599f3515c078fb8c504e13a15b7fabb99">fff775e599f3515c078fb8c504e13a15b7fabb99</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/tiago-ds/liferay-portal/tree/ISSD-1450">ISSD-1450</a><br/>Branch GIT ID: <a href="https://github.com/tiago-ds/liferay-portal/commit/3abce8e8080b910b7794e50998e63a4b0f017166">3abce8e8080b910b7794e50998e63a4b0f017166</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/4977/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/4977/jenkins-report.html">here</a>.</h5></details></html>

2024-01-11 20:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/4977/">test-portal-source-format#4977</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/4977/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5381">is-solutions-delivery#5381</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2487110911">[master] ci:test:sf - tiago-ds &gt; is-solutions-delivery - PR#5381 - 2024-01-11[12:46:22]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2487110911<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/5710/">publish-testray-report#5710</a><br/></div></div>

2024-01-12 12:26 UTC, nNilton requested changes

2024-01-12 12:26 UTC, nNilton commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-etc-cron/src/main/java/com/liferay/learn/Main.java
> +			parsedContent = parsedContent.substring(0, 301) + "...";
you can add a return statement instead of attributing to a variable

2024-01-16 13:47 UTC, joseabelenda commented
resent:https://github.com/brianchandotcom/liferay-portal/pull/146284

2024-01-16 13:47 UTC, closed without merging