ISSD-2814 [Testray] Add logic to not add filter to URL when modal
is-solutions-delivery/liferay-portal pull request #5456
Opened 2024-02-01 21:34 UTC by rafaelfs98

2024-02-01 21:34 UTC, rafaelfs98 commented
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

20 files changed, 407 insertions(+), 16 deletions(-)

![](https://raw.githubusercontent.com/kevenleone/gh/main/images/looks-good.gif)

2024-02-01 21:34 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-02-01 21:35 UTC, rafaelfs98 commented
ci:test:sf

2024-02-01 21:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/4478/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/4478/jenkins-report.html">here</a>.</b></p>

2024-02-01 21:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c720a2bc9c2a31d7f3ecd5144844851331557c4">7c720a2bc9c2a31d7f3ecd5144844851331557c4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaelfs98/liferay-portal/tree/ISSD-2567">ISSD-2567</a><br/>Branch GIT ID: <a href="https://github.com/rafaelfs98/liferay-portal/commit/eceac699d87bb28a4163d1ef756025f3afca1699">eceac699d87bb28a4163d1ef756025f3afca1699</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/4478/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/4478/jenkins-report.html">here</a>.</h5></details></html>

2024-02-01 21:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/4478/">test-portal-source-format#4478</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/4478/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5456">is-solutions-delivery#5456</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2533683541">[master] ci:test:sf - rafaelfs98 &gt; is-solutions-delivery - PR#5456 - 2024-02-01[13:36:06]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2533683541<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/17319/">publish-testray-report#17319</a><br/></div></div>

2024-02-05 12:11 UTC, rafaelfs98 commented
@joseabelenda  or @kevenleone

2024-02-05 13:17 UTC, rafaelfs98 commented
ci:test:sf

2024-02-05 13:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-source-format/6260/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/6260/jenkins-report.html">here</a>.</b></p>

2024-02-05 13:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f0c0398ae46997a576bcd55e8cb9fa39de702f63">f0c0398ae46997a576bcd55e8cb9fa39de702f63</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaelfs98/liferay-portal/tree/ISSD-2567">ISSD-2567</a><br/>Branch GIT ID: <a href="https://github.com/rafaelfs98/liferay-portal/commit/3e84e7a459159e79df17fcb9134019183ceaaef9">3e84e7a459159e79df17fcb9134019183ceaaef9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/6260/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/6260/jenkins-report.html">here</a>.</h5></details></html>

2024-02-05 16:39 UTC, joseabelenda requested changes

2024-02-05 16:39 UTC, joseabelenda commented on workspaces/liferay-testray-workspace/client-extensions/liferay-testray-custom-element/src/components/ManagementToolbar/ManagementToolbarResultsBar.tsx
> +	const handleRemoveItemDoFilter = (itemToRemove: string) => {
Rename.
Please use English instead Portuguese.

2024-02-05 16:40 UTC, joseabelenda commented
resent:https://github.com/is-solutions-delivery/liferay-portal/pull/5468

2024-02-05 16:41 UTC, joseabelenda commented
@rafaelfs98 see my changes
https://github.com/is-solutions-delivery/liferay-portal/pull/5468/commits/4e08a1e676990fefe9090c8645d6b2e6ce85d5b1

2024-02-05 18:48 UTC, kevenleone requested changes
Hey guys @joseabelenda @rafaelfs98 

Sorry for reopening this issue, is just because I forgot the "send" my pending review here.

@rafaelfs98 this looks really nice, good job!

please see my suggestions and analyze if it makes sense for you.

Only thing I disliked is this `isModal` implementation.

For me, ListView should not know about custom logic for Modals, it should be 100% transparent to any use-case.

You can try to find a better name about what you are doing for filters.

Try something like: `ignoreFilters`, `applyFilters: false` (default true).

Something like, but please without`isModal`

You can follow-up this changes here: https://github.com/is-solutions-delivery/liferay-portal/pull/5469

2024-02-05 18:50 UTC, kevenleone commented
You can close after reviewing my suggestion

2024-02-06 11:27 UTC, closed without merging