ISSD-2694 [PRM] Create a Client Extension Spring Boot for Account Sync
is-solutions-delivery/liferay-portal pull request #5475
Opened 2024-02-06 16:52 UTC by thaynam

2024-02-06 16:52 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-02-06 16:58 UTC, thaynam commented
ci:test:sf

2024-02-06 16:58 UTC, thaynam commented
ci:test:stable

2024-02-06 17:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-portal-source-format/3668/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3668/jenkins-report.html">here</a>.</b></p>

2024-02-06 17:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e5cd9b9d7fb5332ad7593caa307e433a35796070">e5cd9b9d7fb5332ad7593caa307e433a35796070</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaynam/liferay-portal/tree/pr-solutions-5466">pr-solutions-5466</a><br/>Branch GIT ID: <a href="https://github.com/thaynam/liferay-portal/commit/ec96bd283ee15151f6720fb2e339501471ec4a24">ec96bd283ee15151f6720fb2e339501471ec4a24</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-source-format/3668/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3668/jenkins-report.html">here</a>.</h5></details></html>

2024-02-06 17:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-1.liferay.com/job/test-portal-source-format/3668/">test-portal-source-format#3668</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/3668/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5475">is-solutions-delivery#5475</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2535430842">[master] ci:test:sf - thaynam &gt; is-solutions-delivery - PR#5475 - 2024-02-06[08:59:14]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2535430842<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/24345/">publish-testray-report#24345</a><br/></div></div>

2024-02-06 17:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/5086/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5086/jenkins-report.html">here</a>.</b></p>

2024-02-06 17:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>stable</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/5087/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5087/jenkins-report.html">here</a>.</b></p>

2024-02-06 18:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/5086/">test-portal-acceptance-pullrequest(master)#5086</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5086/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5475">is-solutions-delivery#5475</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2535520669">[master] ci:test:relevant - thaynam &gt; is-solutions-delivery - PR#5475 - 2024-02-06[09:55:20]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2535520669<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/11154/">publish-testray-report#11154</a><br/></div></div>

2024-02-06 19:04 UTC, jairmedeiros requested changes

2024-02-06 19:05 UTC, jairmedeiros requested changes
Details

2024-02-06 19:24 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/object-definitions/account-sf.json
Rename to proxy-accounts.json

2024-02-06 19:25 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/object-definitions/account-sf.json
> +	"storageType": "salesforce"
```suggestion
	"externalReferenceCode": "Account",
	"label": {
		"en_US": "Proxy Account"
	},
	"name": "ProxyAccount",
	"objectFields": [
		{
			"DBType": "String",
			"businessType": "Text",
			"externalReferenceCode": "Name",
			"indexed": true,
			"indexedAsKeyword": false,
			"label": {
				"en_US": "Name"
			},
			"name": "name",
			"required": false,
			"type": "String"
		}
	],
	"panelCategoryKey": "control_panel.object",
	"pluralLabel": {
		"en_US": "Proxy Accounts"
	},
	"scope": "company",
	"storageType": "salesforce"
```

2024-02-06 19:29 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-etc-spring-boot/src/main/java/com/liferay/partner/QueueListener.java
> +			}
```suggestion
			for (int i = 0; i < partnerLevelJSONArray.length(); i++) {
				JSONObject partnerLevelJSONObject =
					partnerLevelJSONArray.getJSONObject(i);

				JSONObject partnerLevelTypeJSONObject =
					partnerLevelJSONObject.getJSONObject("partnerLevelType");

				String partnerLevelType = partnerLevelTypeJSONObject.optString(
					"key");

				String partnerLevelERC = partnerLevelJSONObject.getString(
					"externalReferenceCode");

				partnerLevelERCs.put(partnerLevelType, partnerLevelERC);
			}
```

2024-02-06 19:30 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-etc-spring-boot/src/main/java/com/liferay/partner/QueueListener.java
> +							_fetchPartnerLevelERCs();
```suggestion
							_getPartnerLevelExternalReferenceCodes();
```

2024-02-06 19:30 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-etc-spring-boot/src/main/java/com/liferay/partner/QueueListener.java
> +						Map<String, String> partnerLevelERCs =
```suggestion
						Map<String, String> partnerLevelExternalReferenceCodes =
```

2024-02-06 19:34 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-etc-spring-boot/src/main/java/com/liferay/partner/QueueListener.java
> +					}
Improve this log.

2024-02-06 19:34 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-etc-spring-boot/src/main/java/com/liferay/partner/QueueListener.java
> +				String accountRegion = "";
```suggestion
				String accountRegion = null;
```

2024-02-06 19:36 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-etc-spring-boot/src/main/java/com/liferay/partner/QueueListener.java
> +
```suggestion
					blabla = _put(
						partnerAccountJSONObject.toString(),
						StringBundler.concat(
							"/o/headless-admin-user/v1.0/accounts",
							"/by-external-reference-code/",
							salesforceAccountKey));

```

2024-02-06 19:39 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-etc-spring-boot/src/main/java/com/liferay/partner/QueueListener.java
> +			).build());
```suggestion
			).build());
```

2024-02-06 19:40 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-etc-spring-boot/src/main/java/com/liferay/partner/QueueListener.java
> +				regionsIDs.put(organizationName, organizationID);
```suggestion
			for (int i = 0; i < organizationsJSONArray.length(); i++) {
				JSONObject organizationJSONObject =
					organizationsJSONArray.getJSONObject(i);

				String organizationName = organizationJSONObject.getString(
					"name");
				Long organizationID = organizationJSONObject.getLong("id");

				regionsIDs.put(organizationName, organizationID);
```

2024-02-06 19:40 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-etc-spring-boot/src/main/java/com/liferay/partner/QueueListener.java
> +	private Map<String, Long> _fetchRegionsIDs() {
```suggestion
	private Map<String, Long> _getRegionsIds() {
```

2024-02-06 20:07 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 31 out of 33 jobs passed in 2 hours 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e5cd9b9d7fb5332ad7593caa307e433a35796070">e5cd9b9d7fb5332ad7593caa307e433a35796070</a></p><details><summary><strong>ci:test:stable - 31 out of 33 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/5087/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1024596/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334738/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/356735/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1024597/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332620/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334741/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333896/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334740/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/806383/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333895/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334736/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/924840/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333887/"><strike>modules-compile-jdk8/0/2</strike></a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334737/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332617/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332619/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/306149/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/356736/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/907647/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332616/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/364854/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/357577/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/833347/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/830481/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332618/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/907646/">playwright-js-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334739/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-mysql57-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/844062/">portal-license-smoke-mysql57-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/332615/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/842612/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/924839/">unit-jdk8_stable/0/0</a></li></ul></li><li>workspaces-compile-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334735/">workspaces-compile-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>31 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5087/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/333887//consoleText">modules-compile-jdk8/0/2</a><pre>  at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:78)
  at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:129)
  at hudson.tasks.BuildStepMonitor\$1.perform(BuildStepMonitor.java:20)
  at hudson.model.AbstractBuild\$AbstractBuildExecution.perform(AbstractBuild.java:744)
  at hudson.model.AbstractBuild\$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
  at hudson.model.Build\$BuildExecution.post2(Build.java:186)
  at hudson.model.AbstractBuild\$AbstractBuildExecution.post(AbstractBuild.java:635)
  at hudson.model.Run.execute(Run.java:1841)
  at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
  at hudson.model.ResourceController.execute(ResourceController.java:97)
  at hudson.model.Executor.run(Executor.java:429)
define: [LabelParameterValue: NODE_NAME=\$\{NODE_NAME\}]
Triggering projects: verification-node
ERROR: Build step failed with exception
java.lang.NullPointerException: no workspace from node hudson.slaves.DumbSlave[cloud-10-0-13-136] which is computer hudson.slaves.SlaveComputer@42dad6b3 and has channel null
  at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:88)
  at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
  at org.jenkinsci.plugins.postbuildscript.processor.Process [...]

2024-02-06 21:15 UTC, thaynam commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-etc-spring-boot/src/main/java/com/liferay/partner/QueueListener.java
> +					}
Any sugestion?

2024-02-15 17:45 UTC, thaynam commented
ci:test:sf

2024-02-15 17:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/5824/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5824/jenkins-report.html">here</a>.</b></p>

2024-02-15 17:51 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/48d9fb4417e27370e69aa0fcc3dfdd88780136d2">48d9fb4417e27370e69aa0fcc3dfdd88780136d2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaynam/liferay-portal/tree/pr-solutions-5466">pr-solutions-5466</a><br/>Branch GIT ID: <a href="https://github.com/thaynam/liferay-portal/commit/5ade8c4f9982752996224b318e41323ec6fda6cb">5ade8c4f9982752996224b318e41323ec6fda6cb</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5824/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5824/jenkins-report.html">here</a>.</h5><pre>     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:291)
[stopwatch] [run.batch.test.action: 1:47.975 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-7/job/test-portal-source-format/5824//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240215095105898.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240215095105898.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null528269029.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null381995109
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 235ms
[junitreport] Deleting: /tmp/null381995109
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 02-15-2024 09:51:09:968 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null528269029.properties

print-gc-logs:
     [echo] 
     [echo] ##
     [echo] ## /tmp/ant-gc.log
     [echo] ##
     [echo] </pre></details></html>

2024-02-19 17:48 UTC, closed without merging