ISSD-2746
is-solutions-delivery/liferay-portal pull request #5484
Opened 2024-02-08 17:43 UTC by eliasantosf

2024-02-08 17:43 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-02-09 17:45 UTC, eliasantosf commented
ci:test:sf

2024-02-09 17:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/3128/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3128/jenkins-report.html">here</a>.</b></p>

2024-02-09 17:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1f9738f51724c37cd78c82028050cc9f61fefc06">1f9738f51724c37cd78c82028050cc9f61fefc06</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/ISSD-2746">ISSD-2746</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/fe01bdbcff8a1c4c51e9a65f226503b1eb3e9296">fe01bdbcff8a1c4c51e9a65f226503b1eb3e9296</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3128/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3128/jenkins-report.html">here</a>.</h5></details></html>

2024-02-09 17:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3128/">test-portal-source-format#3128</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3128/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5484">is-solutions-delivery#5484</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2537125714">[master] ci:test:sf - eliasantosf &gt; is-solutions-delivery - PR#5484 - 2024-02-09[09:45:37]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2537125714<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/22692/">publish-testray-report#22692</a><br/></div></div>

2024-02-16 12:50 UTC, jairmedeiros requested changes

2024-02-16 12:50 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-custom-element/src/common/components/ModalFormatedInformation/ModalFormatedInformation.tsx
> +	sectionTitle?: string;
```suggestion
	title?: string;
```

2024-02-16 12:50 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-custom-element/src/common/components/ModalFormatedInformation/ModalFormatedInformation.tsx
> +	sectionTitle,
```suggestion
	title,
```

2024-02-16 12:50 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-custom-element/src/common/components/ModalFormatedInformation/ModalFormatedInformation.tsx
> +		{sectionTitle && (
```suggestion
		{title && (
```

2024-02-16 12:50 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-custom-element/src/common/components/ModalFormatedInformation/ModalFormatedInformation.tsx
> +				<div className="mb-0 text-paragraph-md">{sectionTitle}</div>
```suggestion
				<div className="mb-0 text-paragraph-md">{title}</div>
```

2024-02-16 12:50 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-custom-element/src/routes/DealRegistrationList/hooks/useGetListItemsFromDealRegistration.tsx
@eliasantosf, those new columns keys were added to table?

2024-02-16 12:50 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-custom-element/src/routes/DealRegistrationList/components/ModalContent/ModalContent.tsx
> +						sectionTitle="General Information"
Instead use a prop, I think it's better to have this Title component here.

2024-02-16 12:50 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-custom-element/src/routes/DealRegistrationList/components/ModalContent/ModalContent.tsx
>  			<div className="d-flex justify-content-end">
```suggestion
			</div>

			<div className="d-flex justify-content-end">
```

2024-02-16 12:50 UTC, jairmedeiros requested changes
Slight changes!

2024-02-20 12:47 UTC, eliasantosf commented
ci:test:sf

2024-02-20 12:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/16e66444b76c8bb1a39aba9a65327dba06746edd">16e66444b76c8bb1a39aba9a65327dba06746edd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/ISSD-2746">ISSD-2746</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/edce783564b7fca95065f8d17668a42f12f00fb6">edce783564b7fca95065f8d17668a42f12f00fb6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/2092/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/2092/jenkins-report.html">here</a>.</h5></details></html>

2024-02-20 13:54 UTC, jairmedeiros requested changes

2024-02-20 13:54 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-custom-element/src/common/components/ModalTitle/ModalTitle.tsx
> +			</>
```suggestion
			<div>
				<div className="mb-0 text-paragraph-md">{title}</div>
				<hr className="mt-0"></hr>
			</div>
```

2024-02-20 13:54 UTC, jairmedeiros commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-custom-element/src/common/components/ModalTitle/ModalTitle.tsx
> +	title?: string;
```suggestion
	title: string;
```

2024-02-20 17:33 UTC, eliasantosf commented on workspaces/liferay-partner-workspace/client-extensions/liferay-partner-custom-element/src/common/components/ModalTitle/ModalTitle.tsx
> +			</>
Done!

2024-02-20 17:34 UTC, eliasantosf commented
ci:test:sf

2024-02-20 17:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/6418/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6418/jenkins-report.html">here</a>.</b></p>

2024-02-20 17:39 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/106d8ae117a45061cf7860ffad20f0bc473d6e21">106d8ae117a45061cf7860ffad20f0bc473d6e21</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/ISSD-2746">ISSD-2746</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/e5fe800174d9d9f628444df57aa5fea79895865e">e5fe800174d9d9f628444df57aa5fea79895865e</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6418/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6418/jenkins-report.html">here</a>.</h5><pre>     [exec] warning "@liferay/npm-scripts &gt; @testing-library/react@12.1.5" has incorrect peer dependency "react@&lt;18.0.0".
     [exec] warning "@liferay/npm-scripts &gt; @testing-library/react@12.1.5" has incorrect peer dependency "react-dom@&lt;18.0.0".
     [exec] warning "@liferay/npm-scripts &gt; liferay-lang-key-dev-loader@1.0.3" has incorrect peer dependency "webpack@^3.0.0 || ^4.0.0".
     [exec] warning "@liferay/npm-scripts &gt; script-ext-html-webpack-plugin@2.1.4" has incorrect peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
     [exec] warning "@liferay/npm-scripts &gt; script-ext-html-webpack-plugin@2.1.4" has incorrect peer dependency "html-webpack-plugin@^3.0.0 || ^4.0.0".
     [exec] [4/4] Building fresh packages...
     [exec] Done in 13.76s.
     [exec] 
     [exec] &gt; Task :portalWorkspacesYarnCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts lint &amp;&amp; liferay-npm-scripts format:check
     [exec] 
     [exec] liferay-partner-workspace/client-extensions/liferay-partner-custom-element/src/routes/DealRegistrationList/components/ModalContent/ModalContent.tsx: BAD
     [exec] Prettier checked 4 files, 1 file has problems
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] &gt; Task :portalWorkspacesYarnCheckFormat FAILED
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':portalWorkspacesYarnCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':portalWorkspacesYarnCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:145)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)</pre></details></html>

2024-02-20 17:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6418/">test-portal-source-format#6418</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6418/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5484">is-solutions-delivery#5484</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2541332942">[master] ci:test:sf - eliasantosf &gt; is-solutions-delivery - PR#5484 - 2024-02-20[09:35:17]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2541332942<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/24565/">publish-testray-report#24565</a><br/></div></div>

2024-02-20 17:47 UTC, eliasantosf commented
ci:test:sf

2024-02-20 21:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/7542/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7542/jenkins-report.html">here</a>.</b></p>

2024-02-20 21:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/106d8ae117a45061cf7860ffad20f0bc473d6e21">106d8ae117a45061cf7860ffad20f0bc473d6e21</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/ISSD-2746">ISSD-2746</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/abcc5b3d3dc919079de940c0003bed6087ea932a">abcc5b3d3dc919079de940c0003bed6087ea932a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/7542/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7542/jenkins-report.html">here</a>.</h5></details></html>

2024-02-20 21:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/7542/">test-portal-source-format#7542</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7542/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5484">is-solutions-delivery#5484</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2541424251">[master] ci:test:sf - eliasantosf &gt; is-solutions-delivery - PR#5484 - 2024-02-20[13:33:23]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2541424251<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/29679/">publish-testray-report#29679</a><br/></div></div>

2024-02-21 18:32 UTC, jairmedeiros commented
ci:test:sf

2024-02-21 18:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/8295/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8295/jenkins-report.html">here</a>.</b></p>

2024-02-21 18:37 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/97039be0c54337fe719879d08bd5f83cb0108456">97039be0c54337fe719879d08bd5f83cb0108456</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/ISSD-2746">ISSD-2746</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/cd5e6e8d3736c5caf54b3b0bd74a5ea8407d60d7">cd5e6e8d3736c5caf54b3b0bd74a5ea8407d60d7</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8295/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8295/jenkins-report.html">here</a>.</h5><pre>     [exec] warning "@liferay/npm-scripts &gt; @testing-library/react@12.1.5" has incorrect peer dependency "react@&lt;18.0.0".
     [exec] warning "@liferay/npm-scripts &gt; @testing-library/react@12.1.5" has incorrect peer dependency "react-dom@&lt;18.0.0".
     [exec] warning "@liferay/npm-scripts &gt; liferay-lang-key-dev-loader@1.0.3" has incorrect peer dependency "webpack@^3.0.0 || ^4.0.0".
     [exec] warning "@liferay/npm-scripts &gt; script-ext-html-webpack-plugin@2.1.4" has incorrect peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
     [exec] warning "@liferay/npm-scripts &gt; script-ext-html-webpack-plugin@2.1.4" has incorrect peer dependency "html-webpack-plugin@^3.0.0 || ^4.0.0".
     [exec] [4/4] Building fresh packages...
     [exec] Done in 7.34s.
     [exec] 
     [exec] &gt; Task :portalWorkspacesYarnCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts lint &amp;&amp; liferay-npm-scripts format:check
     [exec] 
     [exec] liferay-partner-workspace/client-extensions/liferay-partner-custom-element/src/routes/DealRegistrationList/components/ModalContent/ModalContent.tsx: BAD
     [exec] Prettier checked 4 files, 1 file has problems
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] 
     [exec] &gt; Task :portalWorkspacesYarnCheckFormat FAILED
     [exec] Gradle build finished at 2024-02-21 18:36:55.861.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':portalWorkspacesYarnCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':portalWorkspacesYarnCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:145)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)</pre></details></html>

2024-02-21 20:40 UTC, eliasantosf commented
ci:test:sf

2024-02-21 20:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/2680/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2680/jenkins-report.html">here</a>.</b></p>

2024-02-21 20:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/97039be0c54337fe719879d08bd5f83cb0108456">97039be0c54337fe719879d08bd5f83cb0108456</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/eliasantosf/liferay-portal/tree/ISSD-2746">ISSD-2746</a><br/>Branch GIT ID: <a href="https://github.com/eliasantosf/liferay-portal/commit/f486274d6d2ff2c1aec4c1ea2e891fbcd8272e4e">f486274d6d2ff2c1aec4c1ea2e891fbcd8272e4e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2680/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2680/jenkins-report.html">here</a>.</h5></details></html>

2024-02-21 21:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/2680/">test-portal-source-format#2680</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/2680/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5484">is-solutions-delivery#5484</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2542069861">[master] ci:test:sf - eliasantosf &gt; is-solutions-delivery - PR#5484 - 2024-02-21[12:40:26]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2542069861<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/11239/">publish-testray-report#11239</a><br/></div></div>

2024-02-22 14:14 UTC, jairmedeiros commented
ci:forward:force

2024-02-22 14:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9494/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9494/jenkins-report.html">here</a>.</b></p>

2024-02-22 16:40 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 31 out of 32 jobs passed</h3><h3>:x: ci:test:relevant - 68 out of 89 jobs passed in 2 hours 24 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/97039be0c54337fe719879d08bd5f83cb0108456">97039be0c54337fe719879d08bd5f83cb0108456</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/97039be0c54337fe719879d08bd5f83cb0108456">97039be0c54337fe719879d08bd5f83cb0108456</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2542083048">EE Development Acceptance (master) - 373 - 2024-02-20[20:42:08]</a></p><details><summary><strong>ci:test:stable - 31 out of 32 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>build-iw-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764114/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877957/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/857721/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/306453/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312512/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/922575/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/812959/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/922574/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358761/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339274/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764115/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/339272/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/822285/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/922573/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/952396/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/534361/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877955/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/952397/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358762/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/342155/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/312511/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040788/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/922572/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/848667/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1039218/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877954/">playwright-js-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326890/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-mysql57-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/848666/">portal-license-smoke-mysql57-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/534362/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764118/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/848665/">unit-jdk8_stable/0/0</a></li></ul></li><li>workspaces-compile-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/942585/"><strike>workspaces-compile-jdk8/0/0</strike></a></li></ul></li></ul></div><details><summary><strong>31 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 68 out of 89 jobs PASSED</strong></summary><div><h4>21 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/9494/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/764114/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/877957/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1040789/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/342157/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/848686/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/342156/" [...]

2024-02-22 18:05 UTC, jpince commented
workspaces-compile error in stable:
`     [exec] Exception in thread "main" java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-7.3.3-bin.zip failed: timeout`
Seems unrelated

2024-02-23 12:47 UTC, eliasantosf commented
Related to: https://github.com/brianchandotcom/liferay-portal/pull/147471

2024-02-23 12:47 UTC, eliasantosf commented
ci:close

2024-02-23 12:47 UTC, closed without merging