LPD-20247 Updated styles of Solutions Search Page
is-solutions-delivery/liferay-portal pull request #5548
Opened 2024-03-13 19:56 UTC by welitonpe

2024-03-13 19:56 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-03-13 19:56 UTC, welitonpe commented
ci:test:sf

2024-03-13 20:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/7044/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/7044/jenkins-report.html">here</a>.</b></p>

2024-03-13 20:02 UTC, welitonpe commented
ci:test:sf

2024-03-13 20:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/70065ff671a250eaccff2e8792382579d9efdf69">70065ff671a250eaccff2e8792382579d9efdf69</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/LPD-20243">LPD-20243</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/53d63023cade722ebf48038666101161755fbbaa">53d63023cade722ebf48038666101161755fbbaa</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/7044/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/7044/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/layouts/03_solutions_marketplace/35_accelerator_for_professional_associations_and_councils/page-definition.json expected:&lt;...ibre.com&lt;/a&gt;&lt;br /&gt;\n[ ]"
     [java]                                     ...&gt; but was:&lt;...ibre.com&lt;/a&gt;&lt;br /&gt;\n[��]"
     [java]                                     ...&gt;
     [java] 2: Truncated message :
     [java] ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/layouts/03_solutions_marketplace/35_accelerator_for_professional_associations_and_councils/page-definition.json expected:&lt;...    "fragmentStyle": \{[
     [java]             "borderWidth": "0"
     [java]           \},
     [java]           "fragmentViewports": [
     [java]             \{
     [java]               "fragmentViewportStyle": \{
     [java]                 "paddingLeft": "0",
     [java]                 "paddingRight": "0"
     [java]               \},
     [java]               "id": "tablet"
     [java]             \}
     [java]           ],
     [java]           "indexed": true,
     [java]           "layout": \{
     [java]           \}
     [java]         \},
     [java]         "id": "45ee60ae-565e-5290-b691-2e42d08a719f",
     [java]         "pageElements": [
     [java]           \{
     [java]             "definition": \{
     [java]               "fragmentStyle": \{
     [java]                 "backgroundColor": "#F4F6F9",
     [java]                 "borderWidth": "0",
     [java]                 "paddingBottom": "6"
     [java]               \},
     [java]               "fragmentViewports": [
     [java]                 \{
     [java]                   "fragmentViewportStyle": \{
     [java]                     "paddingLeft": "4",
     [java]                     "paddingRight": "4"
     [java]                   \},
     [java]                   "id": "landscapeMobile"
     [java]                 \}
     [java]               ],
     [java]               "indexed": true,
     [java]               "layout": \{
     [java]                 "paddingBottom": 6
     [java]               \}
     [java]             \},
     [java]             "id": "1366eace-1cbb-9a70-5558-881858778933",
     [java]             "pageElements": [
     [java]               \{
     [java]                 "definition": \{
     [java]                   "fragment": \{
     [java]                     "key": "content-container",
     [java]                     "siteKey": "[\$GROUP_KEY\$]"
     [java]                   \},
     [java]                   "fragmentConfig": \{
     [java]                     "background": "",
     [java]                     "backgroundDarkOrLight": "light",
     [java]                     "backgroundImageUrl": "",</pre></details></html>

2024-03-13 20:04 UTC, kevenleone requested changes

2024-03-13 20:04 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/solutions-search-results/ddm-template.ftl
> +		padding:016px;
```suggestion
	.card-image-title-container {
		padding: 16px;
```

2024-03-13 20:04 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/solutions-search-results/ddm-template.ftl
> +	.developer-name-text{
```suggestion
	.developer-name-text {
```

2024-03-13 20:04 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/solutions-search-results/ddm-template.ftl
> +	.solution-search-image{
```suggestion
	.solution-search-image {
```

2024-03-13 20:04 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/solutions-search-results/ddm-template.ftl
> +		object-fit:contain;
```suggestion
		min-width: 293px;
		object-fit: contain;
```

2024-03-13 20:04 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/solutions-search-results/ddm-template.ftl
> +	}
```suggestion
	.solution-search-results-card {
		border-radius: 10px;
		border: 1px solid #E7EFFF;
		min-height: 456px;
		min-width: 293px;
		overflow: hidden;
	}
```

2024-03-13 20:04 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/solutions-search-results/ddm-template.ftl
> +		text-overflow:ellipsis;
```suggestion
		text-overflow: ellipsis;
```

2024-03-13 20:06 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/70065ff671a250eaccff2e8792382579d9efdf69">70065ff671a250eaccff2e8792382579d9efdf69</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/LPD-20243">LPD-20243</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/53d63023cade722ebf48038666101161755fbbaa">53d63023cade722ebf48038666101161755fbbaa</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/6661/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6661/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/layouts/03_solutions_marketplace/35_accelerator_for_professional_associations_and_councils/page-definition.json expected:&lt;...ibre.com&lt;/a&gt;&lt;br /&gt;\n[ ]"
     [java]                                     ...&gt; but was:&lt;...ibre.com&lt;/a&gt;&lt;br /&gt;\n[��]"
     [java]                                     ...&gt;
     [java] 2: Truncated message :
     [java] ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/layouts/03_solutions_marketplace/35_accelerator_for_professional_associations_and_councils/page-definition.json expected:&lt;...    "fragmentStyle": \{[
     [java]             "borderWidth": "0"
     [java]           \},
     [java]           "fragmentViewports": [
     [java]             \{
     [java]               "fragmentViewportStyle": \{
     [java]                 "paddingLeft": "0",
     [java]                 "paddingRight": "0"
     [java]               \},
     [java]               "id": "tablet"
     [java]             \}
     [java]           ],
     [java]           "indexed": true,
     [java]           "layout": \{
     [java]           \}
     [java]         \},
     [java]         "id": "45ee60ae-565e-5290-b691-2e42d08a719f",
     [java]         "pageElements": [
     [java]           \{
     [java]             "definition": \{
     [java]               "fragmentStyle": \{
     [java]                 "backgroundColor": "#F4F6F9",
     [java]                 "borderWidth": "0",
     [java]                 "paddingBottom": "6"
     [java]               \},
     [java]               "fragmentViewports": [
     [java]                 \{
     [java]                   "fragmentViewportStyle": \{
     [java]                     "paddingLeft": "4",
     [java]                     "paddingRight": "4"
     [java]                   \},
     [java]                   "id": "landscapeMobile"
     [java]                 \}
     [java]               ],
     [java]               "indexed": true,
     [java]               "layout": \{
     [java]                 "paddingBottom": 6
     [java]               \}
     [java]             \},
     [java]             "id": "1366eace-1cbb-9a70-5558-881858778933",
     [java]             "pageElements": [
     [java]               \{
     [java]                 "definition": \{
     [java]                   "fragment": \{
     [java]                     "key": "content-container",
     [java]                     "siteKey": "[\$GROUP_KEY\$]"
     [java]                   \},
     [java]                   "fragmentConfig": \{
     [java]                     "background": "",
     [java]                     "backgroundDarkOrLight": "light",
     [java]                     "backgroundImageUrl": "",</pre></details></html>

2024-03-13 20:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/6661/">test-portal-source-format#6661</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6661/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5548">is-solutions-delivery#5548</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2549644235">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5548 - 2024-03-13[13:02:55]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2549644235<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/4441/">publish-testray-report#4441</a><br/></div></div>

2024-03-13 20:14 UTC, welitonpe commented
ci:test:sf

2024-03-13 20:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/9062/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9062/jenkins-report.html">here</a>.</b></p>

2024-03-13 20:18 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/70065ff671a250eaccff2e8792382579d9efdf69">70065ff671a250eaccff2e8792382579d9efdf69</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/LPD-20243">LPD-20243</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/1a3abaef54da55e93f076b0122b8416dc54bfd6d">1a3abaef54da55e93f076b0122b8416dc54bfd6d</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9062/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9062/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/layouts/03_solutions_marketplace/35_accelerator_for_professional_associations_and_councils/page-definition.json expected:&lt;...ibre.com&lt;/a&gt;&lt;br /&gt;\n[ ]"
     [java]                                     ...&gt; but was:&lt;...ibre.com&lt;/a&gt;&lt;br /&gt;\n[ ]"
     [java]                                     ...&gt;
     [java] 2: Truncated message :
     [java] ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/layouts/03_solutions_marketplace/35_accelerator_for_professional_associations_and_councils/page-definition.json expected:&lt;...    "fragmentStyle": \{[
     [java]             "borderWidth": "0"
     [java]           \},
     [java]           "fragmentViewports": [
     [java]             \{
     [java]               "fragmentViewportStyle": \{
     [java]                 "paddingLeft": "0",
     [java]                 "paddingRight": "0"
     [java]               \},
     [java]               "id": "tablet"
     [java]             \}
     [java]           ],
     [java]           "indexed": true,
     [java]           "layout": \{
     [java]           \}
     [java]         \},
     [java]         "id": "45ee60ae-565e-5290-b691-2e42d08a719f",
     [java]         "pageElements": [
     [java]           \{
     [java]             "definition": \{
     [java]               "fragmentStyle": \{
     [java]                 "backgroundColor": "#F4F6F9",
     [java]                 "borderWidth": "0",
     [java]                 "paddingBottom": "6"
     [java]               \},
     [java]               "fragmentViewports": [
     [java]                 \{
     [java]                   "fragmentViewportStyle": \{
     [java]                     "paddingLeft": "4",
     [java]                     "paddingRight": "4"
     [java]                   \},
     [java]                   "id": "landscapeMobile"
     [java]                 \}
     [java]               ],
     [java]               "indexed": true,
     [java]               "layout": \{
     [java]                 "paddingBottom": 6
     [java]               \}
     [java]             \},
     [java]             "id": "1366eace-1cbb-9a70-5558-881858778933",
     [java]             "pageElements": [
     [java]               \{
     [java]                 "definition": \{
     [java]                   "fragment": \{
     [java]                     "key": "content-container",
     [java]                     "siteKey": "[\$GROUP_KEY\$]"
     [java]                   \},
     [java]                   "fragmentConfig": \{
     [java]                     "background": "",
     [java]                     "backgroundDarkOrLight": "light",
     [java]                     "backgroundImageUrl": "",</pre></details></html>

2024-03-13 20:19 UTC, welitonpe commented
ci:test:sf

2024-03-13 20:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/5165/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5165/jenkins-report.html">here</a>.</b></p>

2024-03-13 20:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9062/">test-portal-source-format#9062</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9062/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5548">is-solutions-delivery#5548</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2549648133">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5548 - 2024-03-13[13:15:04]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2549648133<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/34932/">publish-testray-report#34932</a><br/></div></div>

2024-03-13 20:23 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/70065ff671a250eaccff2e8792382579d9efdf69">70065ff671a250eaccff2e8792382579d9efdf69</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/LPD-20243">LPD-20243</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/6b2e4d23f3fdcd73e4f657de26b6e8e3153d9831">6b2e4d23f3fdcd73e4f657de26b6e8e3153d9831</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/5165/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5165/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/layouts/03_solutions_marketplace/35_accelerator_for_professional_associations_and_councils/page-definition.json expected:&lt;...ibre.com&lt;/a&gt;&lt;br /&gt;\n[ ]"
     [java]                                     ...&gt; but was:&lt;...ibre.com&lt;/a&gt;&lt;br /&gt;\n[ ]"
     [java]                                     ...&gt;
     [java] 2: Truncated message :
     [java] ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/layouts/03_solutions_marketplace/35_accelerator_for_professional_associations_and_councils/page-definition.json expected:&lt;...    "fragmentStyle": \{[
     [java]             "borderWidth": "0"
     [java]           \},
     [java]           "fragmentViewports": [
     [java]             \{
     [java]               "fragmentViewportStyle": \{
     [java]                 "paddingLeft": "0",
     [java]                 "paddingRight": "0"
     [java]               \},
     [java]               "id": "tablet"
     [java]             \}
     [java]           ],
     [java]           "indexed": true,
     [java]           "layout": \{
     [java]           \}
     [java]         \},
     [java]         "id": "45ee60ae-565e-5290-b691-2e42d08a719f",
     [java]         "pageElements": [
     [java]           \{
     [java]             "definition": \{
     [java]               "fragmentStyle": \{
     [java]                 "backgroundColor": "#F4F6F9",
     [java]                 "borderWidth": "0",
     [java]                 "paddingBottom": "6"
     [java]               \},
     [java]               "fragmentViewports": [
     [java]                 \{
     [java]                   "fragmentViewportStyle": \{
     [java]                     "paddingLeft": "4",
     [java]                     "paddingRight": "4"
     [java]                   \},
     [java]                   "id": "landscapeMobile"
     [java]                 \}
     [java]               ],
     [java]               "indexed": true,
     [java]               "layout": \{
     [java]                 "paddingBottom": 6
     [java]               \}
     [java]             \},
     [java]             "id": "1366eace-1cbb-9a70-5558-881858778933",
     [java]             "pageElements": [
     [java]               \{
     [java]                 "definition": \{
     [java]                   "fragment": \{
     [java]                     "key": "content-container",
     [java]                     "siteKey": "[\$GROUP_KEY\$]"
     [java]                   \},
     [java]                   "fragmentConfig": \{
     [java]                     "background": "",
     [java]                     "backgroundDarkOrLight": "light",
     [java]                     "backgroundImageUrl": "",</pre></details></html>

2024-03-13 20:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/5165/">test-portal-source-format#5165</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5165/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5548">is-solutions-delivery#5548</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2549648217">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5548 - 2024-03-13[13:20:12]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2549648217<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/20338/">publish-testray-report#20338</a><br/></div></div>

2024-03-13 20:29 UTC, welitonpe commented
ci:test:sf

2024-03-13 20:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/70065ff671a250eaccff2e8792382579d9efdf69">70065ff671a250eaccff2e8792382579d9efdf69</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/LPD-20243">LPD-20243</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/491019906088dccc5a184585795552aa3beb694c">491019906088dccc5a184585795552aa3beb694c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5312/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5312/jenkins-report.html">here</a>.</h5></details></html>

2024-03-13 20:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5312/">test-portal-source-format#5312</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5312/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5548">is-solutions-delivery#5548</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2549650200">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5548 - 2024-03-13[13:30:32]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2549650200<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/20943/">publish-testray-report#20943</a><br/></div></div>

2024-03-13 21:26 UTC, kevenleone commented
ci:forward

2024-03-13 21:26 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-03-13 21:26 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:sf`

2024-03-14 00:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10460/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10460/jenkins-report.html">here</a>.</b></p>

2024-03-14 03:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 34 out of 34 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 65 out of 66 jobs passed in 3 hours 29 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0e018c3cff7dbea91253c05c8a3f05981446ab73">0e018c3cff7dbea91253c05c8a3f05981446ab73</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/70065ff671a250eaccff2e8792382579d9efdf69">70065ff671a250eaccff2e8792382579d9efdf69</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2549744314">EE Development Acceptance (master) - 417 - 2024-03-13[12:41:06]</a></p><details><summary><strong>ci:test:stable - 34 out of 34 jobs PASSED</strong></summary><details><summary><strong>34 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 64 out of 66 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10460/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347963/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313436/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/366683/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/304009/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347967/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350765/">functional-smoke-tomcat90-mysql57-jdk11_open/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347968/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376742/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/304005/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql153-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379345/">functional-smoke-tomcat90-postgresql153-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313431/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379341/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/304006/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/941315/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313433/">functional-tomcat90-mysql57-chrome100-jdk8/1/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334440/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376740/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313435/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347969/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376739/">functional-upgrade-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379344/">functional-upgrade-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350766/">functional-upgrade-tomcat90-mysql57-jdk8/0/6</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/379343/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/402990/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/348132/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/304008/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/402991/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/370961/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</a></li></ul></li><li>functional-upgrade-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334439/">functional-upgrade-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-postgresql153-jdk8<ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/376738/">functional-upgrade-tomcat90-postgresql153-jdk8/0/0</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/334438/">js-unit-jdk8/0/0</a></li></ul></li><li>lpkg-controller-mysql57-jdk8<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/350764/">lpkg-controller-mysql57-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/366681/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/304007/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-16.life [...]

2024-03-14 03:52 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10460//consoleFull)

2024-03-14 03:53 UTC, liferay-continuous-integration commented
Error has occurred while attempting to forward pull request to `brianchandotcom`. Retrying in 1 minute...
See console log for detail:[Full Console](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10460//consoleFull)

2024-03-14 03:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10460/">test-portal-acceptance-pullrequest(master)#10460</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10460/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5548">is-solutions-delivery#5548</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2549811676">[master] ci:test:relevant - welitonpe &gt; is-solutions-delivery - PR#5548 - 2024-03-13[17:21:19]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2549811676<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/21527/">publish-testray-report#21527</a><br/></div></div>

2024-03-14 03:59 UTC, liferay-continuous-integration commented
Error has occurred while attempting to forward pull request to `brianchandotcom`. Retrying in 1 minute...
See console log for detail:[Full Console](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10460//consoleFull)

2024-03-14 04:10 UTC, liferay-continuous-integration commented
Error has occurred while forwarding pull request to `brianchandotcom`.
Please try again later or contact the CI team for assistance.
See console log for details: [Full Console](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10460//consoleFullconsoleText)

2024-03-14 12:49 UTC, kevenleone commented
ci:forward

2024-03-14 12:49 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-03-14 12:49 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2024-03-14 12:51 UTC, closed without merging

2024-03-14 12:51 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/148166
[Console](https://test-1-29.liferay.com/job/forward-pullrequest/992//consoleFull)