ISSD-3256 SF
is-solutions-delivery/liferay-portal pull request #5575
Opened 2024-03-26 16:57 UTC by rafaelfs98

2024-03-26 16:57 UTC, rafaelfs98 commented
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

4 files changed, 27 insertions(+), 1 deletion(-)

![](https://raw.githubusercontent.com/kevenleone/gh/main/images/looks-good.gif)

2024-03-26 16:57 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-03-26 16:58 UTC, rafaelfs98 commented
ci:test:sf

2024-03-26 16:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/5568/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5568/jenkins-report.html">here</a>.</b></p>

2024-03-26 17:25 UTC, JoMaAlves requested changes
🛠️ Needs Review 🛠️
I think there was a mistake there, could you give it a look @rafaelfs98 ?

2024-03-26 17:25 UTC, JoMaAlves commented on workspaces/liferay-testray-workspace/client-extensions/liferay-testray-site-initializer/site-initializer/object-definitions/testray-build.json
> +			"type": "Date"
Is this right? I saw that you added 2 fields with the label "Date Arquived", but one has "startDate" as name and the other "dateArchived". Could you review it?

2024-03-26 17:25 UTC, JoMaAlves commented on workspaces/liferay-testray-workspace/client-extensions/liferay-testray-site-initializer/site-initializer/object-definitions/testray-build.json
> +		},
The other "Date Archived", check the first comment.

2024-03-26 18:04 UTC, JoMaAlves approved these changes
LGTM ​🦖​🌋​ 
Thank you @rafaelfs98

2024-03-26 18:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/7659/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7659/jenkins-report.html">here</a>.</b></p>

2024-03-26 18:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 10 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b6b6d459a89fff752a17d825beafa4e0e884cc52">b6b6d459a89fff752a17d825beafa4e0e884cc52</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaelfs98/liferay-portal/tree/ISSD-3256">ISSD-3256</a><br/>Branch GIT ID: <a href="https://github.com/rafaelfs98/liferay-portal/commit/372d9324085ca6bd17571b34eab13dff59b47444">372d9324085ca6bd17571b34eab13dff59b47444</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/7659/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/7659/jenkins-report.html">here</a>.</h5></details></html>

2024-03-27 20:25 UTC, joseabelenda commented
resent:https://github.com/brianchandotcom/liferay-portal/pull/148585

2024-03-27 20:25 UTC, closed without merging