LPD-20754 Rename and add new properties
is-solutions-delivery/liferay-portal pull request #5613
Opened 2024-04-08 20:22 UTC by kevenleone

2024-04-08 20:22 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-04-11 17:31 UTC, nNilton requested changes

2024-04-11 17:31 UTC, nNilton commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-etc-spring-boot/src/main/java/com/liferay/marketplace/console/service/ConsoleService.java
> +		).post(
refactor to use a generic post

2024-04-11 20:23 UTC, nNilton approved these changes

2024-04-11 23:47 UTC, kevenleone commented
ci:test:sf

2024-04-11 23:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/2902/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2902/jenkins-report.html">here</a>.</b></p>

2024-04-11 23:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/da0175e6eb9c61af012cedeaf57411a1c8933ebd">da0175e6eb9c61af012cedeaf57411a1c8933ebd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/kevenleone/liferay-portal/tree/marketplace-trials">marketplace-trials</a><br/>Branch GIT ID: <a href="https://github.com/kevenleone/liferay-portal/commit/b4d930f0d715267b10d20515ff8ff61e162149d8">b4d930f0d715267b10d20515ff8ff61e162149d8</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2902/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2902/jenkins-report.html">here</a>.</h5></details></html>

2024-04-12 13:31 UTC, kevenleone commented
resent: https://github.com/brianchandotcom/liferay-portal/pull/149157

2024-04-12 13:31 UTC, closed without merging