LPD-23773 Created Trial dashboar and metrics
is-solutions-delivery/liferay-portal pull request #5642
Opened 2024-04-19 20:18 UTC by welitonpe

2024-04-19 20:18 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-04-19 20:20 UTC, welitonpe commented
ci:test:sf

2024-04-19 20:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/6599/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6599/jenkins-report.html">here</a>.</b></p>

2024-04-19 20:24 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/92e97c58318db1faa133bb4bfa79603244a66c92">92e97c58318db1faa133bb4bfa79603244a66c92</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/administrator-dashboard-trial">administrator-dashboard-trial</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/f30db3031f3d156a48de1e9dcdeab1a0896a1f68">f30db3031f3d156a48de1e9dcdeab1a0896a1f68</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6599/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6599/jenkins-report.html">here</a>.</h5><pre>     [exec]   141:2  error  Expected object keys to be in natural ascending order. 'expired' should be before 'get-started'.  sort-keys
     [exec]   252:2  error  Expected object keys to be in natural ascending order. 'recent-trials' should be before 'resources'.  sort-keys
     [exec]   320:2  error  Expected object keys to be in natural ascending order. 'trial-esources' should be before 'trials'.  sort-keys
     [exec] 
     [exec] /opt/dev/projects/github/liferay-portal/workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/AdministratorDashboard/hooks/useTrialMetrics.ts
     [exec]   134:4  error  Expected object keys to be in natural ascending order. 'beforeLastPeriod' should be before 'totalCount'.  sort-keys
     [exec]   140:2  error  Unexpected console statement.  no-console
     [exec]   146:4  error  Expected object keys to be in natural ascending order. 'queue' should be before 'resourcesAvailable'.  sort-keys
     [exec]   155:3  error  Expected object keys to be in natural ascending order. 'expired' should be before 'orders'.  sort-keys
     [exec] 
     [exec] ✖ 8 problems (8 errors, 0 warnings)
     [exec] 
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 1.
     [exec] Gradle build finished at 2024-04-19 20:24:04.511.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':portalWorkspacesYarnCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':portalWorkspacesYarnCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)</pre></details></html>

2024-04-19 20:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6599/">test-portal-source-format#6599</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6599/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5642">is-solutions-delivery#5642</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562199164">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5642 - 2024-04-19[13:20:50]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2562199164<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/25403/">publish-testray-report#25403</a><br/></div></div>

2024-04-19 20:41 UTC, welitonpe commented
ci:test:sf

2024-04-19 20:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/2882/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2882/jenkins-report.html">here</a>.</b></p>

2024-04-19 20:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/92e97c58318db1faa133bb4bfa79603244a66c92">92e97c58318db1faa133bb4bfa79603244a66c92</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/administrator-dashboard-trial">administrator-dashboard-trial</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/2217710ad9460fed8d8d1b8876776d1a14cebdcb">2217710ad9460fed8d8d1b8876776d1a14cebdcb</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2882/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2882/jenkins-report.html">here</a>.</h5></details></html>

2024-04-19 20:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2882/">test-portal-source-format#2882</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2882/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5642">is-solutions-delivery#5642</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562203495">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5642 - 2024-04-19[13:41:47]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2562203495<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/12500/">publish-testray-report#12500</a><br/></div></div>

2024-04-22 12:44 UTC, kevenleone requested changes
Hi @welitonpe can you see my suggestions?

2024-04-22 13:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/2914/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2914/jenkins-report.html">here</a>.</b></p>

2024-04-22 13:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/92e97c58318db1faa133bb4bfa79603244a66c92">92e97c58318db1faa133bb4bfa79603244a66c92</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/administrator-dashboard-trial">administrator-dashboard-trial</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/6ba630406f6c4ec10603f366a876f62a694a309a">6ba630406f6c4ec10603f366a876f62a694a309a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2914/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2914/jenkins-report.html">here</a>.</h5></details></html>

2024-04-22 13:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2914/">test-portal-source-format#2914</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2914/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5642">is-solutions-delivery#5642</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562468558">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5642 - 2024-04-22[06:40:09]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2562468558<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/12456/">publish-testray-report#12456</a><br/></div></div>

2024-04-22 16:43 UTC, kevenleone requested changes

2024-04-22 16:43 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/components/Page.tsx
> +			{(title || description) && (
sort

```suggestion
			{(description || title) && (
```

2024-04-22 16:43 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/enums/Solutions.ts
> +/**
Why Solutions.ts? you can use a name related to the enums here

Order.ts makes more sense

2024-04-22 16:43 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/AdministratorDashboard/pages/Trial/TrialOrderTab/index.tsx
> +type DropDowndItems = {
```suggestion
type DropDownItems = {
```

2024-04-22 16:43 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/AdministratorDashboard/pages/Trial/TrialOrderTab/index.tsx
> +const consoleClouEdnv = 'https://console.liferay.cloud';
```suggestion
const CONSOLE_CLOUD_URL = 'https://console.liferay.cloud';
```

2024-04-22 16:43 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/AdministratorDashboard/pages/Trial/TrialOrderTab/index.tsx
> +const TrialOrderTab: React.FC<AppsTableProps> = ({items}) => {
```suggestion
const TrialTable: React.FC<TrialTableProps> = ({items}) => {
```

2024-04-22 16:43 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/AdministratorDashboard/pages/Trial/TrialOrderTab/index.tsx
> +/**
Rename the folder from `TrialOrderTab` to `TrialTable`

2024-04-22 16:43 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/AdministratorDashboard/pages/Trial/TrialOrderTab/index.tsx
> +type AppsTableProps = {
```suggestion
type TrialTableProps = {
```

2024-04-22 16:43 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/AdministratorDashboard/pages/Trial/TrialOrderTab/index.tsx
> +export default TrialOrderTab;
```suggestion
export default TrialTable;
```

2024-04-22 16:43 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/AdministratorDashboard/pages/Trial/index.tsx
> +					<TrialOrderTab items={orderTableData?.items || []} />
```suggestion
					<TrialTable items={orderTableData?.items || []} />
```

2024-04-22 17:11 UTC, welitonpe commented
ci:test:sf

2024-04-22 17:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/5206/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/5206/jenkins-report.html">here</a>.</b></p>

2024-04-22 17:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/5206/">test-portal-source-format#5206</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/5206/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5642">is-solutions-delivery#5642</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2562526629">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5642 - 2024-04-22[10:12:02]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2562526629<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/5941/">publish-testray-report#5941</a><br/></div></div>

2024-04-22 17:48 UTC, kevenleone commented
Just starting reviewing :)

2024-04-23 01:55 UTC, closed without merging