LRSD-4238 Updated API Usage on Frontend
is-solutions-delivery/liferay-portal pull request #5674
Opened 2024-05-02 19:52 UTC by JoMaAlves

2024-05-02 19:52 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-05-02 20:39 UTC, JoMaAlves commented
ci:test:sf

2024-05-02 20:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/5368/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5368/jenkins-report.html">here</a>.</b></p>

2024-05-02 20:58 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/37f6a49a289d159b46033caf2ee0f61ac8cc25db">37f6a49a289d159b46033caf2ee0f61ac8cc25db</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JoMaAlves/liferay-portal/tree/LRSD-4238">LRSD-4238</a><br/>Branch GIT ID: <a href="https://github.com/JoMaAlves/liferay-portal/commit/1375f92ff555a04c09815b0c0bb8758a549d7589">1375f92ff555a04c09815b0c0bb8758a549d7589</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5368/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5368/jenkins-report.html">here</a>.</h5><pre>     [exec] warning "@liferay/npm-scripts &gt; script-ext-html-webpack-plugin@2.1.4" has incorrect peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
     [exec] warning "@liferay/npm-scripts &gt; script-ext-html-webpack-plugin@2.1.4" has incorrect peer dependency "html-webpack-plugin@^3.0.0 || ^4.0.0".
     [exec] [4/4] Building fresh packages...
     [exec] Done in 12.06s.
     [exec] 
     [exec] &gt; Task :portalWorkspacesYarnCheckFormat FAILED
     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts lint &amp;&amp; liferay-npm-scripts format:check
     [exec] /opt/dev/projects/github/liferay-portal/workspaces/liferay-testray-workspace/client-extensions/liferay-testray-custom-element/src/services/rest/TestraySubtask.ts
     [exec]   10:9  error  'CaseResultStatuses' is defined but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
     [exec]   14:9  error  'testrayCaseResultImpl' is defined but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
     [exec] 
     [exec] ��� 2 problems (2 errors, 0 warnings)
     [exec] 
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] Gradle build finished at 2024-05-02 20:58:25.779.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':portalWorkspacesYarnCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':portalWorkspacesYarnCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)</pre></details></html>

2024-05-02 21:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5368/">test-portal-source-format#5368</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5368/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5674">is-solutions-delivery#5674</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2565243150">[master] ci:test:sf - JoMaAlves &gt; is-solutions-delivery - PR#5674 - 2024-05-02[13:53:14]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2565243150<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/5595/">publish-testray-report#5595</a><br/></div></div>

2024-05-03 14:00 UTC, JoMaAlves commented
ci:test:sf

2024-05-03 14:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/5081/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5081/jenkins-report.html">here</a>.</b></p>

2024-05-03 14:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/5081/">test-portal-source-format#5081</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5081/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5674">is-solutions-delivery#5674</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2565422401">[master] ci:test:sf - JoMaAlves &gt; is-solutions-delivery - PR#5674 - 2024-05-03[07:00:53]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2565422401<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/19690/">publish-testray-report#19690</a><br/></div></div>

2024-05-03 16:09 UTC, joseabelenda requested changes

2024-05-03 16:55 UTC, JoMaAlves commented on workspaces/liferay-testray-workspace/modules/testray-rest-impl/src/main/java/com/liferay/testray/rest/internal/util/TestrayUtil.java
> +	public static int updateSQL(String sql, List<Object> params)
Done!

2024-05-03 16:55 UTC, JoMaAlves commented on workspaces/liferay-testray-workspace/modules/testray-rest-impl/rest-openapi.yaml
> +                amount:
Done!

2024-05-03 16:55 UTC, JoMaAlves commented
ci:test:sf

2024-05-03 16:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/2993/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2993/jenkins-report.html">here</a>.</b></p>

2024-05-03 17:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6ca89c4d994f7bee1786d2999e8455ae80ba340c">6ca89c4d994f7bee1786d2999e8455ae80ba340c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JoMaAlves/liferay-portal/tree/LRSD-4238">LRSD-4238</a><br/>Branch GIT ID: <a href="https://github.com/JoMaAlves/liferay-portal/commit/40070d4907608183b4efb643bececa17492e985b">40070d4907608183b4efb643bececa17492e985b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2993/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2993/jenkins-report.html">here</a>.</h5></details></html>

2024-05-03 17:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2993/">test-portal-source-format#2993</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2993/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5674">is-solutions-delivery#5674</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2565532406">[master] ci:test:sf - JoMaAlves &gt; is-solutions-delivery - PR#5674 - 2024-05-03[09:55:58]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2565532406<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/12706/">publish-testray-report#12706</a><br/></div></div>

2024-05-03 17:12 UTC, JoMaAlves commented
ci:test:sf

2024-05-03 17:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/2994/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2994/jenkins-report.html">here</a>.</b></p>

2024-05-03 17:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6ca89c4d994f7bee1786d2999e8455ae80ba340c">6ca89c4d994f7bee1786d2999e8455ae80ba340c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JoMaAlves/liferay-portal/tree/LRSD-4238">LRSD-4238</a><br/>Branch GIT ID: <a href="https://github.com/JoMaAlves/liferay-portal/commit/ee52cea49d386df308c9f31d68e88361a26af3c0">ee52cea49d386df308c9f31d68e88361a26af3c0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2994/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2994/jenkins-report.html">here</a>.</h5></details></html>

2024-05-03 17:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2994/">test-portal-source-format#2994</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2994/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5674">is-solutions-delivery#5674</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2565535166">[master] ci:test:sf - JoMaAlves &gt; is-solutions-delivery - PR#5674 - 2024-05-03[10:13:11]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2565535166<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/12707/">publish-testray-report#12707</a><br/></div></div>

2024-05-05 14:02 UTC, joseabelenda commented
resent:https://github.com/brianchandotcom/liferay-portal/pull/149972

2024-05-05 14:02 UTC, closed without merging