LPD-26188 Created Templates Blocks and Company
is-solutions-delivery/liferay-portal pull request #5734
Opened 2024-05-24 18:49 UTC by welitonpe

2024-05-24 18:50 UTC, welitonpe commented
ci:test:sf

2024-05-24 18:54 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/63e9cc1b0dfaa0578cb6b690372f7de227ac1c91">63e9cc1b0dfaa0578cb6b690372f7de227ac1c91</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/solutions_details_3">solutions_details_3</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/c98141647d1e7394afdefef7a6ff2da5d9d17e6f">c98141647d1e7394afdefef7a6ff2da5d9d17e6f</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7216/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7216/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 4 formatting issues:
     [java] 1: Truncated message :
     [java] ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/layout-page-templates/display-page-templates/solutions-details/page-definition.json expected:&lt;...eElements": [
     [java]       \{
     [java]   [      "definition": \{
     [java]           "fragmentStyle": \{
     [java]             "backgroundColor": "#F4F6F9",
     [java]             "minHeight": "100vh"
     [java]           \},
     [java]           "indexed": true,
     [java]           "layout": \{
     [java]             "contentDisplay": "FlexColumn"
     [java]           \},
     [java]           "name": "solution-page-container"
     [java]         \},
     [java]         "id": "a75cb294-9350-6b75-7c6d-cac72a885efc",
     [java]         "pageElements": [
     [java]           \{
     [java]             "definition": \{
     [java]               "indexed": true,
     [java]               "layout": \{
     [java]               \}
     [java]             \},
     [java]             "id": "9c6cd20d-f36c-ae67-5817-66e24e8fbfbb",
     [java]             "pageElements": [
     [java]               \{
     [java]                 "definition": \{
     [java]                   "fragmentStyle": \{
     [java]                     "marginBottom": "2.5rem"
     [java]                   \},
     [java]                   "indexed": true,
     [java]                   "layout": \{
     [java]                     "contentDisplay": "FlexColumn"
     [java]                   \},
     [java]                   "name": "solution-page-header"
     [java]                 \},
     [java]                 "id": "a82e8e1e-85f9-3f0a-9a7c-904a6cee43ba",
     [java]                 "pageElements": [
     [java]                   \{
     [java]                     "definition": \{
     [java]                       "indexed": true,
     [java]                       "layout": \{
     [java]                         "widthType": "Fixed"
     [java]                       \},
     [java]                       "name": "Breadcrumb Container"
     [java]                     \},
     [java]                     "id": "e3781102-a791-8e21-7a0d-c5afcaf5769f",
     [java]                     "pageElements": [
     [java]                       \{
     [java]                         "definition": \{
     [java]                           "fragmentStyle": \{
     [java]                             "paddingBottom": "4",
     [java]                             "paddingTop": "4"
     [java]                           \},
     [java]                           "widgetInstance": \{
     [java]                             "widgetConfig": \{
     [java]                             \},
     [java]                             "widgetName": "com_liferay_site_navigation_breadcrumb_web_portlet_SiteNavigationBreadcrumbPortlet"
     [java]                           \}</pre></details></html>

2024-05-24 19:05 UTC, kevenleone commented on modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/marketplace-solutions-blocks/ddm-template.ftl
> +	product = restClient.get("/headless-commerce-delivery-catalog/v1.0/channels/"+ channelId +"/products/"+ productId +"?accountId=-1&images.accountId=-1&nestedFields=productSpecifications,categories,im
```suggestion
	product = restClient.get("/headless-commerce-delivery-catalog/v1.0/channels/"+ channelId +"/products/"+ productId +"?accountId=-1&images.accountId=-1&nestedFields=categories,images,productSpecifications")
```

2024-05-24 20:12 UTC, joanagrego requested changes

2024-05-24 21:10 UTC, welitonpe commented
ci:test:sf

2024-05-24 21:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-8.liferay.com/job/test-portal-source-format/6829/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6829/jenkins-report.html">here</a>.</b></p>

2024-05-24 21:20 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e8cce7c0407de04e791fffa54d37ccb67c6fb604">e8cce7c0407de04e791fffa54d37ccb67c6fb604</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/solutions_details_3">solutions_details_3</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/7919b83899431e202d8e0bddf3a42609e27ec352">7919b83899431e202d8e0bddf3a42609e27ec352</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/6829/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6829/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/marketplace-solutions-header/ddm-template.ftl expected:&lt;...uctSpecifications")
     [java] [
     [java]   catalogName = product.catalogName
     [java]   productImage = product.images![]
     [java]   solutionHeaderImages = productImage?filter(image -&gt; image.tags?seq_contains("solution-header"))
     [java] /&gt;
     [java] 
     [java] &lt;#if product.productSpecifications?has_content&gt;
     [java]   &lt;#assign
     [java]     productSpecifications = product.productSpecifications
     [java] 
     [java]     headerDescription = productSpecifications?filter(specification -&gt; specification.specificationKey == "solution-header-description")[0].value
     [java]     headerTitle = productSpecifications?filter(specification -&gt; specification.specificationKey == "solution-header-title")[0].value
     [java]     hasVideo = productSpecifications?filter(specification -&gt; specification.specificationKey == "solution-header-video-url")
     [java]   /&gt;
     [java] 
     [java]   &lt;#if hasVideo?has_content&gt;
     [java]     &lt;#assign headerVideoUrl = hasVideo[0].value /&gt;
     [java]   &lt;/#if&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#if headerTitle?has_content&gt;
     [java]   &lt;div class="header-content"&gt;
     [java]     &lt;div class="container d-flex"&gt;
     [java]       &lt;div class="mr-5"&gt;
     [java]         &lt;#if headerTitle?has_content&gt;
     [java]           &lt;h1 class="mb-8"&gt;
     [java]             \$\{headerTitle\}
     [java]           &lt;/h1&gt;
     [java]         &lt;/#if&gt;
     [java] 
     [java]         &lt;#if headerDescription?has_content&gt;
     [java]           \$\{headerDescription\}
     [java]         &lt;/#if&gt;
     [java]       &lt;/div&gt;
     [java] 
     [java]       &lt;div&gt;
     [java]         &lt;#if headerVideoUrl?has_content&gt;
     [java]           &lt;#assign videoThumbnail = headerVideoUrl?split("=") /&gt;
     [java] 
     [java]           &lt;a href=" \$\{headerVideoUrl\}" target="_blank"&gt;
     [java]             &lt;div class="align-items-center d-flex justify-content-center position-relative video-preview"&gt;
     [java]               &lt;img
     [java]                 class="video-thumbnail"
     [java]                 aria-label="video-thumbnail"
     [java]                 src="https://img.youtube.com/vi/\$\{videoThumbnail[1]\}/0.jpg" /&gt;
     [java] 
     [java]               &lt;div class="position-absolute video-thumbnail-play-symbol"]&gt;
     [java]                 &lt;@clay["ic...&gt; but was:&lt;...uctSpecifications")</pre></details></html>

2024-05-24 21:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/6829/">test-portal-source-format#6829</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/6829/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5734">is-solutions-delivery#5734</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2571854952">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5734 - 2024-05-24[14:15:52]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2571854952<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/4675/">publish-testray-report#4675</a><br/></div></div>

2024-05-27 13:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/6440/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6440/jenkins-report.html">here</a>.</b></p>

2024-05-27 13:18 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8183183dff07a16b29fcf464b005d372c9f8e060">8183183dff07a16b29fcf464b005d372c9f8e060</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/solutions_details_3">solutions_details_3</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/0586811e398d22623ae3e35fbef2716b0f115dbe">0586811e398d22623ae3e35fbef2716b0f115dbe</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6440/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6440/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: Truncated message :
     [java] ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/marketplace-solutions-company/ddm-template.ftl expected:&lt;...yle&gt;
     [java]   .catalog-icon [\{
     [java]     height: 90px;
     [java]     width: 90px;
     [java]   \}
     [java] 
     [java]   .company-description-container \{
     [java]     width: 846px;
     [java]   \}
     [java] 
     [java]   .company-description-icons-container \{
     [java]     border-radius: 10px;
     [java]     border: solid 1.5px #E2E2E4;
     [java]     width: 846px;
     [java]   \}
     [java] 
     [java]   .company-icon \{
     [java]     height: 48px;
     [java]     width: 48px;
     [java]   \}
     [java] &lt;/style&gt;
     [java] 
     [java] &lt;#if (CPDefinition_cProductId.getData())??&gt;
     [java]   &lt;#assign productId = CPDefinition_cProductId.getData() /&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#if themeDisplay?has_content&gt;
     [java]   &lt;#assign scopeGroupId = themeDisplay.getScopeGroupId() /&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#assign channel = restClient.get("/headless-commerce-delivery-catalog/v1.0/channels?accountId=-1&amp;filter=name eq 'Marketplace Channel' and siteGroupId eq '\$\{scopeGroupId\}'") /&gt;
     [java] 
     [java] &lt;#if channel?has_content&gt;
     [java]   &lt;#assign channelId = channel.items[0].id /&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#assign
     [java]   productId = CPDefinition_cProductId.getData()
     [java]   product = restClient.get("/headless-commerce-delivery-catalog/v1.0/channels/"+ channelId +"/products/"+ productId +"?accountId=-1&amp;images.accountId=-1&amp;nestedFields=categories,images,productSpecifications")
     [java] 
     [java]   catalogName = product.catalogName
     [java]   productImage = product.images![]
     [java]   solutionHeaderImages = productImage?filter(image -&gt; image.tags?seq_contains("solution-profile-app-icon"))
     [java] /&gt;
     [java] 
     [java] &lt;#if product.productSpecifications?has_content&gt;
     [java]   &lt;#assign
     [java]     productSpecifications = product.productSpecifications
     [java] 
     [java]     companyDescriptionSpecification = productSpecifications?filter(specification -&gt; specification.specificationKey == "solution-company-description")</pre></details></html>

2024-05-27 13:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/6440/">test-portal-source-format#6440</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/6440/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5734">is-solutions-delivery#5734</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2572266620">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5734 - 2024-05-27[06:15:29]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2572266620<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/25129/">publish-testray-report#25129</a><br/></div></div>

2024-05-27 13:24 UTC, welitonpe commented
ci:test:sf

2024-05-27 13:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2780/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2780/jenkins-report.html">here</a>.</b></p>

2024-05-27 13:28 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8183183dff07a16b29fcf464b005d372c9f8e060">8183183dff07a16b29fcf464b005d372c9f8e060</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/solutions_details_3">solutions_details_3</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/0889ac221aabbafa62f1d05aa478ec988491c85d">0889ac221aabbafa62f1d05aa478ec988491c85d</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2780/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2780/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: Infinite loop in SourceFormatter: ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/marketplace-solutions-header/ddm-template.ftl
     [java] 2: Truncated message :
     [java] ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/marketplace-solutions-company/ddm-template.ftl expected:&lt;...uctId.getData())??&gt;
     [java] [  &lt;#assign productId = CPDefinition_cProductId.getData() /&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#if themeDisplay?has_content&gt;
     [java]   &lt;#assign scopeGroupId = themeDisplay.getScopeGroupId() /&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#assign channel = restClient.get("/headless-commerce-delivery-catalog/v1.0/channels?accountId=-1&amp;filter=name eq 'Marketplace Channel' and siteGroupId eq '\$\{scopeGroupId\}'") /&gt;
     [java] 
     [java] &lt;#if channel?has_content&gt;
     [java]   &lt;#assign channelId = channel.items[0].id /&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#assign
     [java]   productId = CPDefinition_cProductId.getData()
     [java]   product = restClient.get("/headless-commerce-delivery-catalog/v1.0/channels/"+ channelId +"/products/"+ productId +"?accountId=-1&amp;images.accountId=-1&amp;nestedFields=categories,images,productSpecifications")
     [java] 
     [java]   catalogName = product.catalogName
     [java]   productImage = product.images![]
     [java]   solutionHeaderImages = productImage?filter(image -&gt; image.tags?seq_contains("solution-profile-app-icon"))
     [java] /&gt;
     [java] 
     [java] &lt;#if product.productSpecifications?has_content&gt;
     [java]   &lt;#assign
     [java]     productSpecifications = product.productSpecifications
     [java] 
     [java]     companyDescriptionSpecification = productSpecifications?filter(specification -&gt; specification.specificationKey == "solution-company-description")
     [java]     companyEmailSpecification = productSpecifications?filter(specification -&gt; specification.specificationKey == "solution-company-email")
     [java]     companyPhoneSpecification = productSpecifications?filter(specification -&gt; specification.specificationKey == "solution-company-phone")
     [java]     companyWebsiteSpecification = productSpecifications?filter(specification -&gt; specification.specificationKey == "solution-company-website")
     [java]   /&gt;
     [java] </pre></details></html>

2024-05-27 13:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2780/">test-portal-source-format#2780</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2780/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5734">is-solutions-delivery#5734</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2572269383">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5734 - 2024-05-27[06:24:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2572269383<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/11240/">publish-testray-report#11240</a><br/></div></div>

2024-05-27 13:32 UTC, welitonpe commented
ci:test:sf

2024-05-27 13:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-source-format/5998/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5998/jenkins-report.html">here</a>.</b></p>

2024-05-27 13:37 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8183183dff07a16b29fcf464b005d372c9f8e060">8183183dff07a16b29fcf464b005d372c9f8e060</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/solutions_details_3">solutions_details_3</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/c10c56fbf070cf1632bdc80bb8640647851f0039">c10c56fbf070cf1632bdc80bb8640647851f0039</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5998/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5998/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: Infinite loop in SourceFormatter: ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/marketplace-solutions-header/ddm-template.ftl
     [java] 2: Truncated message :
     [java] ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/marketplace-solutions-blocks/ddm-template.ftl expected:&lt;...-control-prev:hover\{[
     [java]     background: rgb(0, 0, 0);
     [java]   \}
     [java] 
     [java]   .carousel-control-prev:hover \{
     [java]     background: linear-gradient(90deg, rgba(0, 0, 0, 0.3) 0%, rgba(255, 255, 255, 0) 90%);
     [java]     border-radius: 10px;
     [java]     transition: all .3s ease-in-out;
     [java]   \}
     [java] 
     [java]   .carousel-control-next:hover \{
     [java]     background: linear-gradient(-90deg, rgba(0, 0, 0, 0.3) 0%, rgba(255, 255, 255, 0) 90%);
     [java]     border-radius: 10px;
     [java]     transition: all .3s ease-in-out;
     [java]   \}
     [java] 
     [java]   .carousel-indicators li \{
     [java]     border-radius: 50%;
     [java]     border: solid 1px rgba(0, 0, 0, 0.5) !important;
     [java]     height: 10px !important;
     [java]     width: 10px !important;
     [java]   \}
     [java] &lt;/style&gt;
     [java] 
     [java] &lt;#if (CPDefinition_cProductId.getData())??&gt;
     [java]   &lt;#assign productId = CPDefinition_cProductId.getData() /&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#if themeDisplay?has_content&gt;
     [java]   &lt;#assign scopeGroupId = themeDisplay.getScopeGroupId() /&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#assign channel = restClient.get("/headless-commerce-delivery-catalog/v1.0/channels?accountId=-1&amp;filter=name eq 'Marketplace Channel' and siteGroupId eq '\$\{scopeGroupId\}'") /&gt;
     [java] 
     [java] &lt;#if channel?has_content&gt;
     [java]   &lt;#assign channelId = channel.items[0].id /&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#assign
     [java]   productId = CPDefinition_cProductId.getData()
     [java]   product = restClient.get("/headless-commerce-delivery-catalog/v1.0/channels/"+ channelId +"/products/"+ productId +"?accountId=-1&amp;images.accountId=-1&amp;nestedFields=categories,images,productSpecifications")
     [java] 
     [java]   catalogName = product.catalogName
     [java]   productImage = product.images![]
     [java] /&gt;
     [java] </pre></details></html>

2024-05-27 13:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-7.liferay.com/job/test-portal-source-format/5998/">test-portal-source-format#5998</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-source-format/builds/5998/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5734">is-solutions-delivery#5734</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2572270442">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5734 - 2024-05-27[06:33:01]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2572270442<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-7.liferay.com/job/publish-testray-report/3827/">publish-testray-report#3827</a><br/></div></div>

2024-05-27 13:58 UTC, welitonpe commented
ci:test:sf

2024-05-27 13:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2782/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2782/jenkins-report.html">here</a>.</b></p>

2024-05-27 14:01 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d43d79f43544b268573ea5a7d22dbcc5b0a20d2d">d43d79f43544b268573ea5a7d22dbcc5b0a20d2d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/solutions_details_3">solutions_details_3</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/1a91123eafa9ccf94659c355a961a5921a51fbf4">1a91123eafa9ccf94659c355a961a5921a51fbf4</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2782/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2782/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 4 formatting issues:
     [java] 1: Infinite loop in SourceFormatter: ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/marketplace-solutions-blocks/ddm-template.ftl
     [java] 2: Infinite loop in SourceFormatter: ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/marketplace-solutions-header/ddm-template.ftl
     [java] 3: ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/marketplace-solutions-details-page-catalog/ddm-template.ftl expected:&lt;... /&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#assign[
     [java]   productId = CPDefinition_cProductId.getData()
     [java] ]
     [java]   product = restClie...&gt; but was:&lt;... /&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#assign[ productId = CPDefinition_cProductId.getData() /&gt;
     [java] 
     [java] &lt;#assign]
     [java]   product = restClie...&gt;
     [java] 4: Truncated message :
     [java] ./modules/apps/site-initializer/site-initializer-liferay-marketplace/src/main/resources/site-initializer/ddm-templates/marketplace-solutions-company/ddm-template.ftl expected:&lt;...uctId.getData())??&gt;
     [java] [  &lt;#assign productId = CPDefinition_cProductId.getData() /&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#if themeDisplay?has_content&gt;
     [java]   &lt;#assign scopeGroupId = themeDisplay.getScopeGroupId() /&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#assign channel = restClient.get("/headless-commerce-delivery-catalog/v1.0/channels?accountId=-1&amp;filter=name eq 'Marketplace Channel' and siteGroupId eq '\$\{scopeGroupId\}'") /&gt;
     [java] 
     [java] &lt;#if channel?has_content&gt;
     [java]   &lt;#assign channelId = channel.items[0].id /&gt;
     [java] &lt;/#if&gt;
     [java] 
     [java] &lt;#assign
     [java]   productId = CPDefinition_cProductId.getData()
     [java] 
     [java]   product = restClient.get("/headless-commerce-delivery-catalog/v1.0/channels/"+ channelId +"/products/"+ productId +"?accountId=-1&amp;images.accountId=-1&amp;nestedFields=categories,images,productSpecifications")
     [java] 
     [java]   catalogName = product.catalogName
     [java]   productImage = product.images![]
     [java]   solutionHeaderImages = productImage?filter(image -&gt; image.tags?seq_contains("solution-profile-app-icon"))
     [java] /&gt;
     [java] </pre></details></html>

2024-05-27 14:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2782/">test-portal-source-format#2782</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2782/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5734">is-solutions-delivery#5734</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2572274247">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5734 - 2024-05-27[06:58:30]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2572274247<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/11242/">publish-testray-report#11242</a><br/></div></div>

2024-05-30 12:48 UTC, closed without merging