LPD-26191 Adde virtual Donwload Section
is-solutions-delivery/liferay-portal pull request #5768
Opened 2024-05-31 20:35 UTC by welitonpe

2024-05-31 20:35 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-05-31 20:56 UTC, welitonpe commented
ci:test:sf

2024-05-31 20:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/5414/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5414/jenkins-report.html">here</a>.</b></p>

2024-05-31 21:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/548c41c7c7ea4e876b9a422ae1ec7cc47e9609d5">548c41c7c7ea4e876b9a422ae1ec7cc47e9609d5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/download-001">download-001</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/9b4b874ac62e9fa97bb44ae40a14644b506678cd">9b4b874ac62e9fa97bb44ae40a14644b506678cd</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/5414/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5414/jenkins-report.html">here</a>.</h5></details></html>

2024-05-31 21:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/5414/">test-portal-source-format#5414</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/5414/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5768">is-solutions-delivery#5768</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/7993513">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5768 - 2024-05-31[13:56:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>7993513<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/20657/">publish-testray-report#20657</a><br/></div></div>

2024-05-31 21:19 UTC, kevenleone requested changes

2024-05-31 21:19 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/CustomerDashboard/components/PurchasedAppsTable.tsx
> +																`${Liferay.ThemeDisplay.getLayoutURL()}#order/${id}/download`
Use a relative path for this

```suggestion
																`order/${id}/download`
```

2024-05-31 21:19 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/CustomerDashboard/pages/Apps/App/AppOutlet.tsx
> +						data?.placedOrder.workflowStatusInfo.code === 0 &&
Use enum

```suggestion
						data?.placedOrder.workflowStatusInfo.code === 0 &&
```

2024-05-31 21:19 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/CustomerDashboard/pages/Apps/App/Download/Download.tsx
> +	const marketplaceContetx = useMarketplaceContext();
```suggestion
	const marketplaceContext = useMarketplaceContext();
```

2024-05-31 21:19 UTC, kevenleone commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/CustomerDashboard/pages/Apps/App/Download/DownloadTable.tsx
> +	virualItems: VirtualItem[];
```suggestion
	virtualItems: VirtualItem[];
```

2024-06-03 11:32 UTC, joanagrego requested changes

2024-06-03 11:32 UTC, joanagrego commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/CustomerDashboard/components/PurchasedAppsTable.tsx
>  														}
```suggestion
														 if (properties.featureFlags?.includes('LPD-21582') && !isFreeApp) {
    const downloadURL = `${Liferay.ThemeDisplay.getLayoutURL()}#order/${id}/download`;
    Liferay.Util.navigate(downloadURL);
    return;
  }

  if (!virtualURL) {
    Analytics.track('VIRTUAL_URL_NOT_FOUND', metadata);
    alert('Download file not found');
    return;
  }

  Analytics.track('DOWNLOAD_APP', metadata);
  window.open(virtualURL);
```

2024-06-03 11:32 UTC, joanagrego commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/CustomerDashboard/pages/Apps/App/AppOutlet.tsx
> +
is this blank line mandatory?

2024-06-03 11:32 UTC, joanagrego commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/CustomerDashboard/pages/Apps/App/AppOutlet.tsx
> +						data?.placedOrder.placedOrderItems.some(
```suggestion
						placedOrderItems.some(
```

2024-06-03 11:32 UTC, joanagrego commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/CustomerDashboard/pages/Apps/App/Download/Download.tsx
> +			(virtualItem: any) => ({
Can we remove this 'any'?

2024-06-03 11:32 UTC, joanagrego commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/CustomerDashboard/pages/Apps/App/Download/Download.tsx
> +		return virtualItemsWithVersion.filter((item: any) =>
same

2024-06-03 11:32 UTC, joanagrego commented on workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/NextSteps/NextSteps.tsx
>  						}
```suggestion
						
if (
  cart.orderTypeExternalReferenceCode === 'CLOUDAPP' &&
  onClickContinue
) {
  window.location.href = 'https://console.liferay.cloud/projects';
}
```

2024-06-03 13:16 UTC, welitonpe commented
ci:test:sf

2024-06-03 13:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/59431935c110c3274bde292e0587ad8bcd3e2248">59431935c110c3274bde292e0587ad8bcd3e2248</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/download-001">download-001</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/72c2dc0c9cf30efbef5a7ee42c613bb753d28b0e">72c2dc0c9cf30efbef5a7ee42c613bb753d28b0e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6859/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6859/jenkins-report.html">here</a>.</h5></details></html>

2024-06-03 13:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6859/">test-portal-source-format#6859</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6859/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5768">is-solutions-delivery#5768</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/9039683">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#5768 - 2024-06-03[06:17:02]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>9039683<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/26249/">publish-testray-report#26249</a><br/></div></div>

2024-06-03 13:28 UTC, kevenleone approved these changes
LGTM 🔥 

Good job @welitonpe

2024-06-03 13:28 UTC, kevenleone commented
ci:forward

2024-06-03 13:28 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2024-06-03 13:28 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:sf`

2024-06-03 14:32 UTC, kevenleone commented
ci:stop

2024-06-03 14:33 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 82 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.NullPointerException
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/59431935c110c3274bde292e0587ad8bcd3e2248">59431935c110c3274bde292e0587ad8bcd3e2248</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/16979/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/16979/jenkins-report.html">here</a>.</b></p>

2024-06-03 14:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/16979/">test-portal-acceptance-pullrequest(master)#16979</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/16979/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5768">is-solutions-delivery#5768</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/9112883">[master] ci:test:relevant - welitonpe &gt; is-solutions-delivery - PR#5768 - 2024-06-03[06:45:43]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>9112883<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/36580/">publish-testray-report#36580</a><br/></div></div>

2024-06-03 14:46 UTC, kevenleone commented
Just starting reviewing :)

2024-06-03 16:34 UTC, closed without merging