LRSD-4881 Fix Navigation Menu Icons
is-solutions-delivery/liferay-portal pull request #5903
Opened 2024-07-25 18:46 UTC by lluk4z

2024-07-25 18:46 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-07-25 18:48 UTC, lluk4z commented
ci:test:sf

2024-07-25 18:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/9887/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9887/jenkins-report.html">here</a>.</b></p>

2024-07-25 18:53 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/709117be333ef82d320d1c19a9060d9f9e02d17a">709117be333ef82d320d1c19a9060d9f9e02d17a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lluk4z/liferay-portal/tree/LRSD-4881-3">LRSD-4881-3</a><br/>Branch GIT ID: <a href="https://github.com/lluk4z/liferay-portal/commit/5c95a7a9e2d4245e570ccd0ff2e591acaa72ab22">5c95a7a9e2d4245e570ccd0ff2e591acaa72ab22</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9887/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9887/jenkins-report.html">here</a>.</h5><pre>     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ node-scripts format --check
     [exec] 🛫 Running preflight...
     [exec] 📜 Generating tsconfig files...
     [exec] 📜 Validating tsconfig files...
     [exec] 🕵️ Checking modified typescript files...
     [exec] ℹ️ A total of 12 CPUs were detected: launching tsc using 12 workers
     [exec] ℹ️ Going to check 2 modified projects
     [exec] 🕵️ Checking apps/frontend-data-set/frontend-data-set-admin-web
     [exec] 🕵️ Checking apps/object/object-web
     [exec] 
     [exec] ❌ Preflight check failed:
     [exec]    · /opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/package.json: BAD - error thrown during checks: Error: ENOENT: no such file or directory, open '/opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/package.json'
     [exec] 
     [exec] Error
     [exec]     at runPreflight (file:///opt/dev/projects/github/liferay-portal/modules/_node-scripts/preflight/runPreflight.mjs:33:9)
     [exec]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     [exec]     at async main (file:///opt/dev/projects/github/liferay-portal/modules/_node-scripts/format/index.mjs:41:3)
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2024-07-25 18:52:57.389.
     [exec] 3 actionable tasks: 2 executed, 1 up-to-date
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] &gt; Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:148)</pre></details></html>

2024-07-25 18:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9887/">test-portal-source-format#9887</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9887/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5903">is-solutions-delivery#5903</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/45614498">[master] ci:test:sf - lluk4z &gt; is-solutions-delivery - PR#5903 - 2024-07-25[11:48:52]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>45614498<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/37848/">publish-testray-report#37848</a><br/></div></div>

2024-07-26 15:06 UTC, joseabelenda requested changes
@lluk4z

2024-07-26 15:06 UTC, joseabelenda commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-global-css/assets/global.css
> +    }
@lluk4z use tab to indent instead blank spaces.
Please resend.

2024-07-26 16:38 UTC, closed without merging