LRSD-5531 Breadcrumb container in article pages is centralized and not top aligned
is-solutions-delivery/liferay-portal pull request #5919
Opened 2024-08-01 20:13 UTC by lluk4z

2024-08-01 20:13 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-08-01 20:13 UTC, lluk4z commented
ci:test:sf

2024-08-01 20:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/5750/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5750/jenkins-report.html">here</a>.</b></p>

2024-08-01 20:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3a38b9895b23f60a08a89f40db3e9713c737a3f9">3a38b9895b23f60a08a89f40db3e9713c737a3f9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lluk4z/liferay-portal/tree/LRSD-5531">LRSD-5531</a><br/>Branch GIT ID: <a href="https://github.com/lluk4z/liferay-portal/commit/a959b14fb49766230c699e2f172c84c21ba857c3">a959b14fb49766230c699e2f172c84c21ba857c3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/5750/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5750/jenkins-report.html">here</a>.</h5></details></html>

2024-08-01 20:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/5750/">test-portal-source-format#5750</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/5750/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5919">is-solutions-delivery#5919</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/51305232">[master] ci:test:sf - lluk4z &gt; is-solutions-delivery - PR#5919 - 2024-08-01[13:13:36]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>51305232<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/22206/">publish-testray-report#22206</a><br/></div></div>

2024-08-01 21:05 UTC, luisacmn requested changes
@lluk4z on global.css, the padding-top is also affecting the recipe page. We need to change it to affect only the article one.

2024-08-02 11:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/9933/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9933/jenkins-report.html">here</a>.</b></p>

2024-08-02 11:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cb15712f7384223187cdf04de5400594fc3ae1d3">cb15712f7384223187cdf04de5400594fc3ae1d3</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lluk4z/liferay-portal/tree/LRSD-5531">LRSD-5531</a><br/>Branch GIT ID: <a href="https://github.com/lluk4z/liferay-portal/commit/7cba0d5791f7df83610723bbce7527168c1df824">7cba0d5791f7df83610723bbce7527168c1df824</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9933/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9933/jenkins-report.html">here</a>.</h5></details></html>

2024-08-02 11:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/9933/">test-portal-source-format#9933</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/9933/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/5919">is-solutions-delivery#5919</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/34754/routines/34756/build/51726728">[master] ci:test:sf - lluk4z &gt; is-solutions-delivery - PR#5919 - 2024-08-02[04:39:03]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>51726728<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/37982/">publish-testray-report#37982</a><br/></div></div>

2024-08-02 16:27 UTC, luisacmn approved these changes

2024-08-05 18:21 UTC, closed without merging