LRSD-6871
is-solutions-delivery/liferay-portal pull request #6032
Opened 2024-10-22 18:27 UTC by GabrielFernandoS

2024-10-22 18:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/9225/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/9225/jenkins-report.html">here</a>.</b></p>

2024-10-22 18:34 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/20c16b763e47400f6e4d7cc1f462a054278d1d4b">20c16b763e47400f6e4d7cc1f462a054278d1d4b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/GabrielFernandoS/liferay-portal/tree/LRSD-6871">LRSD-6871</a><br/>Branch GIT ID: <a href="https://github.com/GabrielFernandoS/liferay-portal/commit/a9e163491bff1d37a8ba28a1d46275251f5e30ac">a9e163491bff1d37a8ba28a1d46275251f5e30ac</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/9225/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/9225/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found formatting issue in SHA a9e163491bff1d37a8ba28a1d46275251f5e30ac
     [java] The commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSD, ISSITES, LCD, LHC, LOOP, LPD, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, LRSD, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin source-formatter.properties in the liferay-portal repository.
     [java]   at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:62)
     [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1321)
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:338)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:302)
[stopwatch] [run.batch.test.action: 1:38.882 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
      [get] Getting: http://test-1-32/job/test-portal-source-format/9225//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20241022113411276.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20241022113411276.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1076918634.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null942861783
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 170ms
[junitreport] Deleting: /tmp/null942861783
     [echo] A report with all the test results can be found at test-results/html/index.html.</pre></details></html>

2024-10-22 18:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/9225/">test-portal-source-format#9225</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/9225/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/6032">is-solutions-delivery#6032</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/49104575">[master] ci:test:sf - GabrielFernandoS &gt; is-solutions-delivery - PR#6032 - 2024-10-22[11:30:59]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>49104575<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/34722/">publish-testray-report#34722</a><br/></div></div>

2024-10-22 19:07 UTC, nNilton commented
ci:test:sf

2024-10-22 19:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/6770/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6770/jenkins-report.html">here</a>.</b></p>

2024-10-22 19:11 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/98a3dd7975ecd032ef566f2e5bd0e26be20a0d35">98a3dd7975ecd032ef566f2e5bd0e26be20a0d35</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/GabrielFernandoS/liferay-portal/tree/LRSD-6871">LRSD-6871</a><br/>Branch GIT ID: <a href="https://github.com/GabrielFernandoS/liferay-portal/commit/540444eeb37635b20dc90b3fa9e3c3cc1cdabf64">540444eeb37635b20dc90b3fa9e3c3cc1cdabf64</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6770/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6770/jenkins-report.html">here</a>.</h5></details></html>

2024-10-22 19:41 UTC, rtienpal commented
Please sort (576px goes in front of768px)

2024-10-22 20:15 UTC, lluk4z commented
ci:test:sf

2024-10-22 20:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/75cdfe67b3f03ae0eaaddbcb91187877e279f954">75cdfe67b3f03ae0eaaddbcb91187877e279f954</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/GabrielFernandoS/liferay-portal/tree/LRSD-6871">LRSD-6871</a><br/>Branch GIT ID: <a href="https://github.com/GabrielFernandoS/liferay-portal/commit/ec7d66bea182acb12096bbdea0bf87f2ec81494b">ec7d66bea182acb12096bbdea0bf87f2ec81494b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6771/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6771/jenkins-report.html">here</a>.</h5></details></html>

2024-10-22 20:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/6771/">test-portal-source-format#6771</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/6771/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/6032">is-solutions-delivery#6032</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/49274366">[master] ci:test:sf - GabrielFernandoS &gt; is-solutions-delivery - PR#6032 - 2024-10-22[13:15:41]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>49274366<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/25184/">publish-testray-report#25184</a><br/></div></div>

2024-10-23 16:28 UTC, nNilton requested changes

2024-10-23 16:28 UTC, nNilton commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-global-css/assets/global.css
> +      line-height: normal;
please sort these items alfabetically

2024-10-23 17:02 UTC, nNilton commented
ci:test:sf

2024-10-23 17:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/10421/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10421/jenkins-report.html">here</a>.</b></p>

2024-10-23 17:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/449fa8fd0fbf5b9bbae254fdd8b549332370371e">449fa8fd0fbf5b9bbae254fdd8b549332370371e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/GabrielFernandoS/liferay-portal/tree/LRSD-6871">LRSD-6871</a><br/>Branch GIT ID: <a href="https://github.com/GabrielFernandoS/liferay-portal/commit/5179fe92b7aac3f32f52df66b2fe6333cdde141f">5179fe92b7aac3f32f52df66b2fe6333cdde141f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/10421/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10421/jenkins-report.html">here</a>.</h5></details></html>

2024-10-23 18:46 UTC, nNilton commented
ci:test:sf

2024-10-23 18:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/6524/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6524/jenkins-report.html">here</a>.</b></p>

2024-10-23 18:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/453a71da18c89e9b2773b8a615afa46ce1a5d22d">453a71da18c89e9b2773b8a615afa46ce1a5d22d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/GabrielFernandoS/liferay-portal/tree/LRSD-6871">LRSD-6871</a><br/>Branch GIT ID: <a href="https://github.com/GabrielFernandoS/liferay-portal/commit/3d7100e6ea6e3ef7015b2901e80fed793bcc2082">3d7100e6ea6e3ef7015b2901e80fed793bcc2082</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6524/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6524/jenkins-report.html">here</a>.</h5></details></html>

2024-10-23 18:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/6524/">test-portal-source-format#6524</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/6524/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/6032">is-solutions-delivery#6032</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/50053208">[master] ci:test:sf - GabrielFernandoS &gt; is-solutions-delivery - PR#6032 - 2024-10-23[11:46:53]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>50053208<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/24926/">publish-testray-report#24926</a><br/></div></div>

2024-10-24 20:02 UTC, nNilton commented
resent:https://github.com/brianchandotcom/liferay-portal/pull/155538

2024-10-24 20:02 UTC, closed without merging