LPD-37874 SF
is-solutions-delivery/liferay-portal pull request #6075
Opened 2024-12-06 14:24 UTC by welitonpe

2024-12-06 14:24 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-12-06 14:24 UTC, welitonpe commented
ci:test:sf

2024-12-06 14:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/3801/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3801/jenkins-report.html">here</a>.</b></p>

2024-12-06 14:29 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/aa5ff49f6773055856e47fd07c0dc12c31da0ace">aa5ff49f6773055856e47fd07c0dc12c31da0ace</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/welitonpe/liferay-portal/tree/test55">test55</a><br/>Branch GIT ID: <a href="https://github.com/welitonpe/liferay-portal/commit/98efa93788bfe24978071a6d52eda7eb9715f345">98efa93788bfe24978071a6d52eda7eb9715f345</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3801/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3801/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found formatting issue in SHA 276abdd31e73f56c34891826d8d0255b34c785aa
     [java] The commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSD, ISSITES, LCD, LHC, LOOP, LPD, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, LRSD, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin source-formatter.properties in the liferay-portal repository.
     [java]   at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:62)
     [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1320)
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:337)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 1:56.341 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1608916570.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null84448454
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 156ms
[junitreport] Deleting: /tmp/null84448454
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 12-06-2024 06:29:09:550 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2024-12-06 14:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/3801/">test-portal-source-format#3801</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/3801/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/6075">is-solutions-delivery#6075</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/85498504">[master] ci:test:sf - welitonpe &gt; is-solutions-delivery - PR#6075 - 2024-12-06[06:25:12]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>85498504<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/15579/">publish-testray-report#15579</a><br/></div></div>

2024-12-10 19:05 UTC, kevenleone requested changes
Good job @welitonpe I see a lot of work in here.

Please fix the points I've suggested and we'll do another sync later

2024-12-10 19:05 UTC, kevenleone commented on modules/apps/commerce/commerce-channel-web/src/main/resources/META-INF/resources/js/paymentMethod_instalation/components/PaymentMethodModal.tsx
> +	);
```suggestion
      if (!open) {
          return null;
      }

	return (
		<ClayModal
			center
			className="clay-modal-refector"
			observer={observer}
			size="full-screen"
		>
			<ClayModal.Header>
				{Liferay.Language.get('add-from-marketplace')}
			</ClayModal.Header>

			<ClayModal.Body className="m-0 p-0">
				{step === PAYMENT_VIEW.list && (
					<InstallPaymentMethodModalBody
						loading={loading}
						pagination={pagination}
						products={items}
						searchQuery={pagination.searchQuery}
						setSearchQuery={pagination.setSearchQuery}
						setSelectedApp={setSelectedApp}
						setStep={setStep}
					/>
				)}

				{step === PAYMENT_VIEW.details && selectedApp && (
					<AppDetails
						backToList={setStep}
						product={selectedApp}
					/>
				)}
			</ClayModal.Body>
		</ClayModal>
	);
```

2024-12-10 19:05 UTC, kevenleone commented on modules/apps/commerce/commerce-channel-web/src/main/resources/META-INF/resources/js/paymentMethod_instalation/hooks/useProducts.ts
> +	];
Move outside component

2024-12-10 19:05 UTC, kevenleone commented on modules/apps/commerce/commerce-channel-web/src/main/resources/META-INF/resources/js/paymentMethod_instalation/hooks/useProducts.ts
> +const sortIcon = {
```suggestion
const SORT_ICON = {
```

2024-12-10 19:05 UTC, kevenleone commented on modules/apps/commerce/commerce-channel-web/src/main/resources/META-INF/resources/js/paymentMethod_instalation/hooks/useProducts.ts
> +					`https://marketplace-uat.liferay.com/o/headless-admin-taxonomy/v1.0/taxonomy-vocabularies/${11730462}/taxonomy-categories`
```suggestion
					`https://marketplace-uat.liferay.com/o/headless-admin-taxonomy/v1.0/taxonomy-vocabularies/${ADD_A_VARIABLE_HERE_WITH_THIS_VALUE}/taxonomy-categories`
```

2024-12-10 19:05 UTC, kevenleone commented on modules/apps/commerce/commerce-channel-web/src/main/resources/META-INF/resources/js/paymentMethod_instalation/hooks/useProducts.ts
> +			}
No need for finally

just add this at the end of the function

2024-12-10 19:05 UTC, kevenleone commented on modules/apps/commerce/commerce-channel-web/src/main/resources/META-INF/resources/js/paymentMethod_instalation/hooks/useProducts.ts
> +						'x-csrf-token': Liferay.authToken,
Not the same Liferay to use this token

```suggestion
```

2024-12-10 19:05 UTC, kevenleone commented on modules/apps/commerce/commerce-channel-web/src/main/resources/META-INF/resources/js/paymentMethod_instalation/style/appDetails.scss
> +	// max-width: var(--container-max-xl, 1248px);
remove comment

2024-12-10 19:05 UTC, kevenleone commented on modules/apps/commerce/commerce-channel-web/src/main/resources/META-INF/resources/js/paymentMethod_instalation/hooks/useProducts.ts
> +
delete comments

2024-12-10 19:05 UTC, kevenleone commented on modules/apps/commerce/commerce-channel-web/src/main/resources/META-INF/resources/js/paymentMethod_instalation/hooks/useProducts.ts
> +	}, [searchQuery]);
Create or use a debounce hook, search for it in the portal or copy from Marketplace

2024-12-13 02:47 UTC, kevenleone commented
Just starting reviewing :)

2024-12-18 21:08 UTC, closed without merging