LRSD-7363
is-solutions-delivery/liferay-portal pull request #6084
Opened 2024-12-12 17:23 UTC by GabrielFernandoS

2024-12-12 17:26 UTC, rtienpal commented
ci:test:sf

2024-12-12 17:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/7153/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7153/jenkins-report.html">here</a>.</b></p>

2024-12-12 17:31 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/986e895f85625d5d84a61d88de4458af3f59b595">986e895f85625d5d84a61d88de4458af3f59b595</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/GabrielFernandoS/liferay-portal/tree/LRSD-7363">LRSD-7363</a><br/>Branch GIT ID: <a href="https://github.com/GabrielFernandoS/liferay-portal/commit/2929ac93817c6524051d90ccd579b9d375d8863e">2929ac93817c6524051d90ccd579b9d375d8863e</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7153/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7153/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./workspaces/liferay-learn-workspace/client-extensions/liferay-learn-global-css/assets/global.css expected:&lt;...put::placeholder \{
     [java]   [color: var(--color-state-neutral-darken-1,#6C6C75 ) !important;
     [java]   font-size: 1rem !important;
     [java]   font-weight: 400 !important;
     [java]   line-height: 24px] !important;
     [java] \}
     [java] 
     [java] .lea...&gt; but was:&lt;...put::placeholder \{
     [java]   [line-height: 24px !important;
     [java]   color: var(--color-state-neutral-darken-1,#6C6C75 ) !important;
     [java]   font-weight: 400 !important;
     [java]   font-size: 1rem] !important;
     [java] \}
     [java] 
     [java] .lea...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:472)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 2:07.836 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null317718508.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null387855099
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 223ms
[junitreport] Deleting: /tmp/null387855099
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results</pre></details></html>

2024-12-12 17:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7153/">test-portal-source-format#7153</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7153/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/6084">is-solutions-delivery#6084</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/90388463">[master] ci:test:sf - GabrielFernandoS &gt; is-solutions-delivery - PR#6084 - 2024-12-12[09:27:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>90388463<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/26077/">publish-testray-report#26077</a><br/></div></div>

2024-12-12 17:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/7154/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7154/jenkins-report.html">here</a>.</b></p>

2024-12-12 17:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/7154/">test-portal-source-format#7154</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/7154/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/6084">is-solutions-delivery#6084</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/90412824">[master] ci:test:sf - GabrielFernandoS &gt; is-solutions-delivery - PR#6084 - 2024-12-12[09:43:03]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>90412824<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/26078/">publish-testray-report#26078</a><br/></div></div>

2024-12-12 17:52 UTC, rtienpal commented
ci:test:sf

2024-12-12 17:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/9428/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/9428/jenkins-report.html">here</a>.</b></p>

2024-12-12 17:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/986e895f85625d5d84a61d88de4458af3f59b595">986e895f85625d5d84a61d88de4458af3f59b595</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/GabrielFernandoS/liferay-portal/tree/LRSD-7363">LRSD-7363</a><br/>Branch GIT ID: <a href="https://github.com/GabrielFernandoS/liferay-portal/commit/c472689274d11a2fc0ece28c7c63aee21b8c8cac">c472689274d11a2fc0ece28c7c63aee21b8c8cac</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/9428/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/9428/jenkins-report.html">here</a>.</h5></details></html>

2024-12-12 17:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/9428/">test-portal-source-format#9428</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/9428/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/6084">is-solutions-delivery#6084</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/90414418">[master] ci:test:sf - GabrielFernandoS &gt; is-solutions-delivery - PR#6084 - 2024-12-12[09:52:41]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>90414418<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/35448/">publish-testray-report#35448</a><br/></div></div>

2024-12-12 19:08 UTC, joseabelenda requested changes
@GabrielFernandoS please read my comments.
Thx

2024-12-12 19:08 UTC, joseabelenda commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-global-css/assets/global.css
> +  font-weight: 400;
@GabrielFernandoS please align it.
SF

2024-12-12 19:08 UTC, joseabelenda commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-global-css/assets/global.css
> +.panel-title {
Sort

2024-12-12 19:08 UTC, joseabelenda commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-global-css/assets/global.css
> +.treeview .btn {
Sort

2024-12-12 19:08 UTC, joseabelenda commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-global-css/assets/global.css
> +}
Remove space

2024-12-12 19:08 UTC, joseabelenda commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-global-css/assets/global.css
> +.input-group .search-bar-keywords-input::placeholder {
Sort

2024-12-12 19:58 UTC, lluk4z commented
ci:test:sf

2024-12-12 20:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5c56fee234cbc11ca74f5ce843d4e291b6cbc5c6">5c56fee234cbc11ca74f5ce843d4e291b6cbc5c6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/GabrielFernandoS/liferay-portal/tree/LRSD-7363">LRSD-7363</a><br/>Branch GIT ID: <a href="https://github.com/GabrielFernandoS/liferay-portal/commit/95d8fe145776a1119c2c996200cc367fb8bc6acf">95d8fe145776a1119c2c996200cc367fb8bc6acf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-8.liferay.com/job/test-portal-source-format/7434/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7434/jenkins-report.html">here</a>.</h5></details></html>

2024-12-12 20:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-8.liferay.com/job/test-portal-source-format/7434/">test-portal-source-format#7434</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-8.liferay.com/userContent/jobs/test-portal-source-format/builds/7434/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/is-solutions-delivery/liferay-portal/pull/6084">is-solutions-delivery#6084</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/90454725">[master] ci:test:sf - GabrielFernandoS &gt; is-solutions-delivery - PR#6084 - 2024-12-12[11:58:19]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>90454725<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-8.liferay.com/job/publish-testray-report/5385/">publish-testray-report#5385</a><br/></div></div>

2024-12-17 14:32 UTC, joseabelenda commented
resent:https://github.com/brianchandotcom/liferay-portal/pull/157072

2024-12-17 14:32 UTC, closed without merging